// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.Item;
namespace VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\storage\raft\snapshot-auto\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VaultApi.Client.sys.storage.raft.snapshotAuto.status.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/storage/raft/snapshot-auto/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/storage/raft/snapshot-auto/status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
