// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.RekeyRecoveryKey.Init;
using VaultApi.Client.Sys.RekeyRecoveryKey.Update;
using VaultApi.Client.Sys.RekeyRecoveryKey.Verify;
namespace VaultApi.Client.Sys.RekeyRecoveryKey
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\rekey-recovery-key
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RekeyRecoveryKeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The init property</summary>
        public global::VaultApi.Client.Sys.RekeyRecoveryKey.Init.InitRequestBuilder Init
        {
            get => new global::VaultApi.Client.Sys.RekeyRecoveryKey.Init.InitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::VaultApi.Client.Sys.RekeyRecoveryKey.Update.UpdateRequestBuilder Update
        {
            get => new global::VaultApi.Client.Sys.RekeyRecoveryKey.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::VaultApi.Client.Sys.RekeyRecoveryKey.Verify.VerifyRequestBuilder Verify
        {
            get => new global::VaultApi.Client.Sys.RekeyRecoveryKey.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.RekeyRecoveryKey.RekeyRecoveryKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RekeyRecoveryKeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/rekey-recovery-key", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.RekeyRecoveryKey.RekeyRecoveryKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RekeyRecoveryKeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/rekey-recovery-key", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
