// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Auth.Userpass.Login;
using VaultApi.Client.Auth.Userpass.Users;
namespace VaultApi.Client.Auth.Userpass
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\userpass
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserpassRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::VaultApi.Client.Auth.Userpass.Login.LoginRequestBuilder Login
        {
            get => new global::VaultApi.Client.Auth.Userpass.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::VaultApi.Client.Auth.Userpass.Users.UsersRequestBuilder Users
        {
            get => new global::VaultApi.Client.Auth.Userpass.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Auth.Userpass.UserpassRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserpassRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/userpass", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Auth.Userpass.UserpassRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserpassRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/userpass", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
