// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Auth.Token.Accessors;
using VaultApi.Client.Auth.Token.Create;
using VaultApi.Client.Auth.Token.CreateOrphan;
using VaultApi.Client.Auth.Token.Lookup;
using VaultApi.Client.Auth.Token.LookupAccessor;
using VaultApi.Client.Auth.Token.LookupSelf;
using VaultApi.Client.Auth.Token.Renew;
using VaultApi.Client.Auth.Token.RenewAccessor;
using VaultApi.Client.Auth.Token.RenewSelf;
using VaultApi.Client.Auth.Token.Revoke;
using VaultApi.Client.Auth.Token.RevokeAccessor;
using VaultApi.Client.Auth.Token.RevokeOrphan;
using VaultApi.Client.Auth.Token.RevokeSelf;
using VaultApi.Client.Auth.Token.Roles;
using VaultApi.Client.Auth.Token.Tidy;
namespace VaultApi.Client.Auth.Token
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\token
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accessors property</summary>
        public global::VaultApi.Client.Auth.Token.Accessors.AccessorsRequestBuilder Accessors
        {
            get => new global::VaultApi.Client.Auth.Token.Accessors.AccessorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token create path is used to create new tokens.</summary>
        public global::VaultApi.Client.Auth.Token.Create.CreateRequestBuilder Create
        {
            get => new global::VaultApi.Client.Auth.Token.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token create path is used to create new orphan tokens.</summary>
        public global::VaultApi.Client.Auth.Token.CreateOrphan.CreateOrphanRequestBuilder CreateOrphan
        {
            get => new global::VaultApi.Client.Auth.Token.CreateOrphan.CreateOrphanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will lookup a token and its properties.</summary>
        public global::VaultApi.Client.Auth.Token.Lookup.LookupRequestBuilder Lookup
        {
            get => new global::VaultApi.Client.Auth.Token.Lookup.LookupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will lookup a token associated with the given accessor and its properties. Response will not contain the token ID.</summary>
        public global::VaultApi.Client.Auth.Token.LookupAccessor.LookupAccessorRequestBuilder LookupAccessor
        {
            get => new global::VaultApi.Client.Auth.Token.LookupAccessor.LookupAccessorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will lookup a token and its properties.</summary>
        public global::VaultApi.Client.Auth.Token.LookupSelf.LookupSelfRequestBuilder LookupSelf
        {
            get => new global::VaultApi.Client.Auth.Token.LookupSelf.LookupSelfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will renew the given token and prevent expiration.</summary>
        public global::VaultApi.Client.Auth.Token.Renew.RenewRequestBuilder Renew
        {
            get => new global::VaultApi.Client.Auth.Token.Renew.RenewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will renew a token associated with the given accessor and its properties. Response will not contain the token ID.</summary>
        public global::VaultApi.Client.Auth.Token.RenewAccessor.RenewAccessorRequestBuilder RenewAccessor
        {
            get => new global::VaultApi.Client.Auth.Token.RenewAccessor.RenewAccessorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will renew the token used to call it and prevent expiration.</summary>
        public global::VaultApi.Client.Auth.Token.RenewSelf.RenewSelfRequestBuilder RenewSelf
        {
            get => new global::VaultApi.Client.Auth.Token.RenewSelf.RenewSelfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will delete the given token and all of its child tokens.</summary>
        public global::VaultApi.Client.Auth.Token.Revoke.RevokeRequestBuilder Revoke
        {
            get => new global::VaultApi.Client.Auth.Token.Revoke.RevokeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will delete the token associated with the accessor and all of its child tokens.</summary>
        public global::VaultApi.Client.Auth.Token.RevokeAccessor.RevokeAccessorRequestBuilder RevokeAccessor
        {
            get => new global::VaultApi.Client.Auth.Token.RevokeAccessor.RevokeAccessorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will delete the token and orphan its child tokens.</summary>
        public global::VaultApi.Client.Auth.Token.RevokeOrphan.RevokeOrphanRequestBuilder RevokeOrphan
        {
            get => new global::VaultApi.Client.Auth.Token.RevokeOrphan.RevokeOrphanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint will delete the token used to call it and all of its child tokens.</summary>
        public global::VaultApi.Client.Auth.Token.RevokeSelf.RevokeSelfRequestBuilder RevokeSelf
        {
            get => new global::VaultApi.Client.Auth.Token.RevokeSelf.RevokeSelfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::VaultApi.Client.Auth.Token.Roles.RolesRequestBuilder Roles
        {
            get => new global::VaultApi.Client.Auth.Token.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>This endpoint performs cleanup tasks that can be run if certain error conditions have occurred.</summary>
        public global::VaultApi.Client.Auth.Token.Tidy.TidyRequestBuilder Tidy
        {
            get => new global::VaultApi.Client.Auth.Token.Tidy.TidyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Auth.Token.TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/token", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Auth.Token.TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/token", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
