// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Replication.Primary.Demote;
using VaultApi.Client.Sys.Replication.Primary.Disable;
using VaultApi.Client.Sys.Replication.Primary.Enable;
using VaultApi.Client.Sys.Replication.Primary.RevokeSecondary;
using VaultApi.Client.Sys.Replication.Primary.SecondaryToken;
namespace VaultApi.Client.Sys.Replication.Primary
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\replication\primary
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PrimaryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The demote property</summary>
        public global::VaultApi.Client.Sys.Replication.Primary.Demote.DemoteRequestBuilder Demote
        {
            get => new global::VaultApi.Client.Sys.Replication.Primary.Demote.DemoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disable property</summary>
        public global::VaultApi.Client.Sys.Replication.Primary.Disable.DisableRequestBuilder Disable
        {
            get => new global::VaultApi.Client.Sys.Replication.Primary.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enable property</summary>
        public global::VaultApi.Client.Sys.Replication.Primary.Enable.EnableRequestBuilder Enable
        {
            get => new global::VaultApi.Client.Sys.Replication.Primary.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The revokeSecondary property</summary>
        public global::VaultApi.Client.Sys.Replication.Primary.RevokeSecondary.RevokeSecondaryRequestBuilder RevokeSecondary
        {
            get => new global::VaultApi.Client.Sys.Replication.Primary.RevokeSecondary.RevokeSecondaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secondaryToken property</summary>
        public global::VaultApi.Client.Sys.Replication.Primary.SecondaryToken.SecondaryTokenRequestBuilder SecondaryToken
        {
            get => new global::VaultApi.Client.Sys.Replication.Primary.SecondaryToken.SecondaryTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Primary.PrimaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrimaryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/primary", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Primary.PrimaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrimaryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/primary", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
