// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Quotas.Config;
using VaultApi.Client.Sys.Quotas.LeaseCount;
using VaultApi.Client.Sys.Quotas.RateLimit;
namespace VaultApi.Client.Sys.Quotas
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\quotas
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuotasRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Create, update and read the quota configuration.</summary>
        public global::VaultApi.Client.Sys.Quotas.Config.ConfigRequestBuilder Config
        {
            get => new global::VaultApi.Client.Sys.Quotas.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leaseCount property</summary>
        public global::VaultApi.Client.Sys.Quotas.LeaseCount.LeaseCountRequestBuilder LeaseCount
        {
            get => new global::VaultApi.Client.Sys.Quotas.LeaseCount.LeaseCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rateLimit property</summary>
        public global::VaultApi.Client.Sys.Quotas.RateLimit.RateLimitRequestBuilder RateLimit
        {
            get => new global::VaultApi.Client.Sys.Quotas.RateLimit.RateLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Quotas.QuotasRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuotasRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/quotas", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Quotas.QuotasRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuotasRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/quotas", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
