// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VaultApi.Client.Auth.Jwt.Role
{
    /// <summary>Lists all the roles registered with the backend.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetListQueryParameterType
    {
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        True,
        #pragma warning restore CS1591
    }
}
