// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Quotas.RateLimit.Item;
namespace VaultApi.Client.Sys.Quotas.RateLimit
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\quotas\rate-limit
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RateLimitRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Lists the names of all the rate limit quotas.</summary>
        public global::VaultApi.Client.Sys.Quotas.RateLimit.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Sys.Quotas.RateLimit.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Get, create or update rate limit resource quota for an optional namespace or mount.</summary>
        /// <param name="position">Name of the quota rule.</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Quotas.RateLimit.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Quotas.RateLimit.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Sys.Quotas.RateLimit.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Quotas.RateLimit.RateLimitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RateLimitRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/quotas/rate-limit", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Quotas.RateLimit.RateLimitRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RateLimitRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/quotas/rate-limit", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
