// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VaultApi.Client.Sys.Pprof.Allocs;
using VaultApi.Client.Sys.Pprof.Block;
using VaultApi.Client.Sys.Pprof.Cmdline;
using VaultApi.Client.Sys.Pprof.Goroutine;
using VaultApi.Client.Sys.Pprof.Heap;
using VaultApi.Client.Sys.Pprof.Mutex;
using VaultApi.Client.Sys.Pprof.Profile;
using VaultApi.Client.Sys.Pprof.Symbol;
using VaultApi.Client.Sys.Pprof.Threadcreate;
using VaultApi.Client.Sys.Pprof.Trace;
namespace VaultApi.Client.Sys.Pprof
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\pprof
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PprofRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allocs property</summary>
        public global::VaultApi.Client.Sys.Pprof.Allocs.AllocsRequestBuilder Allocs
        {
            get => new global::VaultApi.Client.Sys.Pprof.Allocs.AllocsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The block property</summary>
        public global::VaultApi.Client.Sys.Pprof.Block.BlockRequestBuilder Block
        {
            get => new global::VaultApi.Client.Sys.Pprof.Block.BlockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cmdline property</summary>
        public global::VaultApi.Client.Sys.Pprof.Cmdline.CmdlineRequestBuilder Cmdline
        {
            get => new global::VaultApi.Client.Sys.Pprof.Cmdline.CmdlineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The goroutine property</summary>
        public global::VaultApi.Client.Sys.Pprof.Goroutine.GoroutineRequestBuilder Goroutine
        {
            get => new global::VaultApi.Client.Sys.Pprof.Goroutine.GoroutineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The heap property</summary>
        public global::VaultApi.Client.Sys.Pprof.Heap.HeapRequestBuilder Heap
        {
            get => new global::VaultApi.Client.Sys.Pprof.Heap.HeapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mutex property</summary>
        public global::VaultApi.Client.Sys.Pprof.Mutex.MutexRequestBuilder Mutex
        {
            get => new global::VaultApi.Client.Sys.Pprof.Mutex.MutexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::VaultApi.Client.Sys.Pprof.Profile.ProfileRequestBuilder Profile
        {
            get => new global::VaultApi.Client.Sys.Pprof.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The symbol property</summary>
        public global::VaultApi.Client.Sys.Pprof.Symbol.SymbolRequestBuilder Symbol
        {
            get => new global::VaultApi.Client.Sys.Pprof.Symbol.SymbolRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threadcreate property</summary>
        public global::VaultApi.Client.Sys.Pprof.Threadcreate.ThreadcreateRequestBuilder Threadcreate
        {
            get => new global::VaultApi.Client.Sys.Pprof.Threadcreate.ThreadcreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tracePath property</summary>
        public global::VaultApi.Client.Sys.Pprof.Trace.TraceRequestBuilder TracePath
        {
            get => new global::VaultApi.Client.Sys.Pprof.Trace.TraceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Pprof.PprofRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PprofRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/pprof", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Pprof.PprofRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PprofRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/pprof", rawUrl)
        {
        }
        /// <summary>
        /// Returns an HTML page listing the available profiles. This should be mainly accessed via browsers or applications that can render pages.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an HTML page listing the available profiles. This should be mainly accessed via browsers or applications that can render pages.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Pprof.PprofRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VaultApi.Client.Sys.Pprof.PprofRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VaultApi.Client.Sys.Pprof.PprofRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PprofRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
