// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.Activate;
using VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.Deactivate;
namespace VaultApi.Client.Sys.ActivationFlags.OauthResourceServer
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\activation-flags\oauth-resource-server
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OauthResourceServerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activate property</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.Activate.ActivateRequestBuilder Activate
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.Activate.ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deactivate property</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.Deactivate.DeactivateRequestBuilder Deactivate
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.Deactivate.DeactivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.OauthResourceServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthResourceServerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/activation-flags/oauth-resource-server", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.OauthResourceServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthResourceServerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/activation-flags/oauth-resource-server", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
