// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Identity.Mfa.LoginEnforcement.Item;
namespace VaultApi.Client.Identity.Mfa.LoginEnforcement
{
    /// <summary>
    /// Builds and executes requests for operations under \identity\mfa\login-enforcement
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginEnforcementRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The EmptyPathSegment property</summary>
        public global::VaultApi.Client.Identity.Mfa.LoginEnforcement.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Identity.Mfa.LoginEnforcement.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the VaultApi.Client.identity.mfa.loginEnforcement.item collection</summary>
        /// <param name="position">Name for this login enforcement configuration</param>
        /// <returns>A <see cref="global::VaultApi.Client.Identity.Mfa.LoginEnforcement.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Identity.Mfa.LoginEnforcement.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Identity.Mfa.LoginEnforcement.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Mfa.LoginEnforcement.LoginEnforcementRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginEnforcementRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/mfa/login-enforcement", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Mfa.LoginEnforcement.LoginEnforcementRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginEnforcementRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/mfa/login-enforcement", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
