// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.ControlGroup.Authorize;
using VaultApi.Client.Sys.ControlGroup.Request;
namespace VaultApi.Client.Sys.ControlGroup
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\control-group
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ControlGroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::VaultApi.Client.Sys.ControlGroup.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::VaultApi.Client.Sys.ControlGroup.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The request property</summary>
        public global::VaultApi.Client.Sys.ControlGroup.Request.RequestRequestBuilder Request
        {
            get => new global::VaultApi.Client.Sys.ControlGroup.Request.RequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ControlGroup.ControlGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ControlGroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/control-group", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ControlGroup.ControlGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ControlGroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/control-group", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
