// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Identity.Oidc.Key.Item;
namespace VaultApi.Client.Identity.Oidc.Key
{
    /// <summary>
    /// Builds and executes requests for operations under \identity\oidc\key
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>List OIDC keys</summary>
        public global::VaultApi.Client.Identity.Oidc.Key.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Identity.Oidc.Key.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>CRUD operations for OIDC keys.</summary>
        /// <param name="position">Name of the key</param>
        /// <returns>A <see cref="global::VaultApi.Client.Identity.Oidc.Key.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Identity.Oidc.Key.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Identity.Oidc.Key.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Oidc.Key.KeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/oidc/key", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Oidc.Key.KeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/oidc/key", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
