// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Namespaces.ApiLock;
using VaultApi.Client.Sys.Namespaces.Item;
namespace VaultApi.Client.Sys.Namespaces
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\namespaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NamespacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apiLock property</summary>
        public global::VaultApi.Client.Sys.Namespaces.ApiLock.ApiLockRequestBuilder ApiLock
        {
            get => new global::VaultApi.Client.Sys.Namespaces.ApiLock.ApiLockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::VaultApi.Client.Sys.Namespaces.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Sys.Namespaces.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the VaultApi.Client.sys.namespaces.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Namespaces.Item.WithPathItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Namespaces.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::VaultApi.Client.Sys.Namespaces.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Namespaces.NamespacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NamespacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/namespaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Namespaces.NamespacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NamespacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/namespaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
