// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Policies.Acl;
using VaultApi.Client.Sys.Policies.Egp;
using VaultApi.Client.Sys.Policies.Password;
using VaultApi.Client.Sys.Policies.Rgp;
namespace VaultApi.Client.Sys.Policies
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\policies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PoliciesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acl property</summary>
        public global::VaultApi.Client.Sys.Policies.Acl.AclRequestBuilder Acl
        {
            get => new global::VaultApi.Client.Sys.Policies.Acl.AclRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The egp property</summary>
        public global::VaultApi.Client.Sys.Policies.Egp.EgpRequestBuilder Egp
        {
            get => new global::VaultApi.Client.Sys.Policies.Egp.EgpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The password property</summary>
        public global::VaultApi.Client.Sys.Policies.Password.PasswordRequestBuilder Password
        {
            get => new global::VaultApi.Client.Sys.Policies.Password.PasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rgp property</summary>
        public global::VaultApi.Client.Sys.Policies.Rgp.RgpRequestBuilder Rgp
        {
            get => new global::VaultApi.Client.Sys.Policies.Rgp.RgpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Policies.PoliciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PoliciesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/policies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Policies.PoliciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PoliciesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/policies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
