// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.ActivationFlags.ActivationTest.Activate;
namespace VaultApi.Client.Sys.ActivationFlags.ActivationTest
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\activation-flags\activation-test
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivationTestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Returns information about Vault&apos;s features that require a one-time activation step.</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.ActivationTest.Activate.ActivateRequestBuilder Activate
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.ActivationTest.Activate.ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ActivationFlags.ActivationTest.ActivationTestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivationTestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/activation-flags/activation-test", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ActivationFlags.ActivationTest.ActivationTestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivationTestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/activation-flags/activation-test", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
