// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Internal.Inspect.Router.Item;
namespace VaultApi.Client.Sys.Internal.Inspect.Router
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\internal\inspect\router
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RouterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Information on the entries in each of the trees in the router. Inspectable trees are uuid, accessor, storage, and root.</summary>
        /// <param name="position">Name of subtree being observed</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Internal.Inspect.Router.Item.WithTagItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Internal.Inspect.Router.Item.WithTagItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tag", position);
                return new global::VaultApi.Client.Sys.Internal.Inspect.Router.Item.WithTagItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.Inspect.Router.RouterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RouterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal/inspect/router", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.Inspect.Router.RouterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RouterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal/inspect/router", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
