// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Mfa.MethodNamespace.Totp.Item;
namespace VaultApi.Client.Sys.Mfa.MethodNamespace.Totp
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\mfa\method\totp
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TotpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VaultApi.Client.sys.mfa.method.totp.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Mfa.MethodNamespace.Totp.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Mfa.MethodNamespace.Totp.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Sys.Mfa.MethodNamespace.Totp.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Mfa.MethodNamespace.Totp.TotpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TotpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/mfa/method/totp", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Mfa.MethodNamespace.Totp.TotpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TotpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/mfa/method/totp", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
