---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.api.port_http | int | toString }}"
  POSTGRESDB_HOST: "{{ .Values.config.api.POSTGRESDB_HOST }}"
  POSTGRESDB_PORT: "{{ .Values.config.api.POSTGRESDB_PORT }}"
  POSTGRESDB_USERNAME: "{{ .Values.config.api.POSTGRESDB_USERNAME }}"
  POSTGRESDB_JDBCCONNECTIONSTRING: "{{ .Values.config.api.POSTGRESDB_JDBCCONNECTIONSTRING }}"
  POSTGRESDB_DATABASENAME: "{{ .Values.config.api.POSTGRESDB_DATABASENAME }}"
  Vault__Address: "{{ .Values.config.api.Vault__Address }}"
  VITE_APP_HTTP: "{{ .Values.config.api.VITE_APP_HTTP }}"
  services__vite-app__http__0: "{{ .Values.config.api.services__vite_app__http__0 }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.api.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ .Values.config.api.OTEL_EXPORTER_OTLP_PROTOCOL }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.api.OTEL_SERVICE_NAME }}"
