---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__postgresdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.api.postgres_password }};Database=postgresdb"
  POSTGRESDB_PASSWORD: "{{ .Values.secrets.api.postgres_password }}"
  POSTGRESDB_URI: "postgresql://postgres:{{ .Values.secrets.api.postgres_password }}@postgres-service:5432/postgresdb"
  Vault__Token: "{{ .Values.secrets.api.vault_token }}"
type: "Opaque"
