// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Identity.Oidc.Scope.Item;
namespace VaultApi.Client.Identity.Oidc.Scope
{
    /// <summary>
    /// Builds and executes requests for operations under \identity\oidc\scope
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScopeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>List OIDC scopes</summary>
        public global::VaultApi.Client.Identity.Oidc.Scope.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Identity.Oidc.Scope.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>CRUD operations for OIDC scopes.</summary>
        /// <param name="position">Name of the scope</param>
        /// <returns>A <see cref="global::VaultApi.Client.Identity.Oidc.Scope.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Identity.Oidc.Scope.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Identity.Oidc.Scope.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Oidc.Scope.ScopeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScopeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/oidc/scope", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Oidc.Scope.ScopeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScopeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/oidc/scope", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
