// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload.Item;
namespace VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\replication\dr\secondary\config\reload
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VaultApi.Client.sys.replication.dr.secondary.config.reload.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload.Item.WithSubsystemItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload.Item.WithSubsystemItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("subsystem", position);
                return new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload.Item.WithSubsystemItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload.ReloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/dr/secondary/config/reload", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.Reload.ReloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/dr/secondary/config/reload", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
