// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuthReadConfigurationResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Accessor { get; set; }
#nullable restore
#else
        public string Accessor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.AuthReadConfigurationResponse_config? Config { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.AuthReadConfigurationResponse_config Config { get; set; }
#endif
        /// <summary>The deprecation_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeprecationStatus { get; set; }
#nullable restore
#else
        public string DeprecationStatus { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The external_entropy_access property</summary>
        public bool? ExternalEntropyAccess { get; set; }
        /// <summary>The local property</summary>
        public bool? Local { get; set; }
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.AuthReadConfigurationResponse_options? Options { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.AuthReadConfigurationResponse_options Options { get; set; }
#endif
        /// <summary>The plugin_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PluginVersion { get; set; }
#nullable restore
#else
        public string PluginVersion { get; set; }
#endif
        /// <summary>The running_plugin_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunningPluginVersion { get; set; }
#nullable restore
#else
        public string RunningPluginVersion { get; set; }
#endif
        /// <summary>The running_sha256 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunningSha256 { get; set; }
#nullable restore
#else
        public string RunningSha256 { get; set; }
#endif
        /// <summary>The seal_wrap property</summary>
        public bool? SealWrap { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The uuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.AuthReadConfigurationResponse"/> and sets the default values.
        /// </summary>
        public AuthReadConfigurationResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.AuthReadConfigurationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.AuthReadConfigurationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.AuthReadConfigurationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessor", n => { Accessor = n.GetStringValue(); } },
                { "config", n => { Config = n.GetObjectValue<global::VaultApi.Client.Models.AuthReadConfigurationResponse_config>(global::VaultApi.Client.Models.AuthReadConfigurationResponse_config.CreateFromDiscriminatorValue); } },
                { "deprecation_status", n => { DeprecationStatus = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "external_entropy_access", n => { ExternalEntropyAccess = n.GetBoolValue(); } },
                { "local", n => { Local = n.GetBoolValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::VaultApi.Client.Models.AuthReadConfigurationResponse_options>(global::VaultApi.Client.Models.AuthReadConfigurationResponse_options.CreateFromDiscriminatorValue); } },
                { "plugin_version", n => { PluginVersion = n.GetStringValue(); } },
                { "running_plugin_version", n => { RunningPluginVersion = n.GetStringValue(); } },
                { "running_sha256", n => { RunningSha256 = n.GetStringValue(); } },
                { "seal_wrap", n => { SealWrap = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessor", Accessor);
            writer.WriteObjectValue<global::VaultApi.Client.Models.AuthReadConfigurationResponse_config>("config", Config);
            writer.WriteStringValue("deprecation_status", DeprecationStatus);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("external_entropy_access", ExternalEntropyAccess);
            writer.WriteBoolValue("local", Local);
            writer.WriteObjectValue<global::VaultApi.Client.Models.AuthReadConfigurationResponse_options>("options", Options);
            writer.WriteStringValue("plugin_version", PluginVersion);
            writer.WriteStringValue("running_plugin_version", RunningPluginVersion);
            writer.WriteStringValue("running_sha256", RunningSha256);
            writer.WriteBoolValue("seal_wrap", SealWrap);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
