// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntityMergeRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Alias IDs to keep in case of conflicting aliases. Ignored if no conflicting aliases found</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ConflictingAliasIdsToKeep { get; set; }
#nullable restore
#else
        public List<string> ConflictingAliasIdsToKeep { get; set; }
#endif
        /// <summary>Setting this will follow the &apos;mine&apos; strategy for merging MFA secrets. If there are secrets of the same type both in entities that are merged from and in entity into which all others are getting merged, secrets in the destination will be unaltered. If not set, this API will throw an error containing all the conflicts.</summary>
        public bool? Force { get; set; }
        /// <summary>Entity IDs which need to get merged</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FromEntityIds { get; set; }
#nullable restore
#else
        public List<string> FromEntityIds { get; set; }
#endif
        /// <summary>Entity ID into which all the other entities need to get merged</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToEntityId { get; set; }
#nullable restore
#else
        public string ToEntityId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.EntityMergeRequest"/> and sets the default values.
        /// </summary>
        public EntityMergeRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.EntityMergeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.EntityMergeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.EntityMergeRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conflicting_alias_ids_to_keep", n => { ConflictingAliasIdsToKeep = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "force", n => { Force = n.GetBoolValue(); } },
                { "from_entity_ids", n => { FromEntityIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "to_entity_id", n => { ToEntityId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("conflicting_alias_ids_to_keep", ConflictingAliasIdsToKeep);
            writer.WriteBoolValue("force", Force);
            writer.WriteCollectionOfPrimitiveValues<string>("from_entity_ids", FromEntityIds);
            writer.WriteStringValue("to_entity_id", ToEntityId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
