// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntityUpdateAliasByIdRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Entity ID to which this alias should be tied to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanonicalId { get; set; }
#nullable restore
#else
        public string CanonicalId { get; set; }
#endif
        /// <summary>User provided key-value pairs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest_custom_metadata? CustomMetadata { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest_custom_metadata CustomMetadata { get; set; }
#endif
        /// <summary>Entity ID to which this alias belongs to. This field is deprecated, use canonical_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>Unique external identifier from external IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Issuer name associated with this alias.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Issuer { get; set; }
#nullable restore
#else
        public string Issuer { get; set; }
#endif
        /// <summary>(Unused)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MountAccessor { get; set; }
#nullable restore
#else
        public string MountAccessor { get; set; }
#endif
        /// <summary>(Unused)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest"/> and sets the default values.
        /// </summary>
        public EntityUpdateAliasByIdRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canonical_id", n => { CanonicalId = n.GetStringValue(); } },
                { "custom_metadata", n => { CustomMetadata = n.GetObjectValue<global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest_custom_metadata>(global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest_custom_metadata.CreateFromDiscriminatorValue); } },
                { "entity_id", n => { EntityId = n.GetStringValue(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "issuer", n => { Issuer = n.GetStringValue(); } },
                { "mount_accessor", n => { MountAccessor = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("canonical_id", CanonicalId);
            writer.WriteObjectValue<global::VaultApi.Client.Models.EntityUpdateAliasByIdRequest_custom_metadata>("custom_metadata", CustomMetadata);
            writer.WriteStringValue("entity_id", EntityId);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteStringValue("issuer", Issuer);
            writer.WriteStringValue("mount_accessor", MountAccessor);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
