// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateRandomWithSourceAndBytesRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of bytes to generate (POST body parameter). Defaults to 32 (256 bits).</summary>
        public int? Bytes { get; set; }
        /// <summary>If set, seed a secure DRBG from the source and use it to generate the bytes. This can be more performant when using the seal source. Possible values are unset (don&apos;t use a DRBG), &quot;auto&quot; and &quot;hmacdrbg&quot; which are equivalent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Drbg { get; set; }
#nullable restore
#else
        public string Drbg { get; set; }
#endif
        /// <summary>Encoding format to use. Can be &quot;hex&quot; or &quot;base64&quot;. Defaults to &quot;base64&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.GenerateRandomWithSourceAndBytesRequest"/> and sets the default values.
        /// </summary>
        public GenerateRandomWithSourceAndBytesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Format = "base64";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.GenerateRandomWithSourceAndBytesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.GenerateRandomWithSourceAndBytesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.GenerateRandomWithSourceAndBytesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bytes", n => { Bytes = n.GetIntValue(); } },
                { "drbg", n => { Drbg = n.GetStringValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bytes", Bytes);
            writer.WriteStringValue("drbg", Drbg);
            writer.WriteStringValue("format", Format);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
