// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InternalClientActivityConfigureRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of months to report if no start date specified.</summary>
        [Obsolete("")]
        public int? DefaultReportMonths { get; set; }
        /// <summary>Enable or disable collection of client count: enable, disable, or default.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Enabled { get; set; }
#nullable restore
#else
        public string Enabled { get; set; }
#endif
        /// <summary>Number of months of client data to retain. Setting to 0 will clear all existing data.</summary>
        public int? RetentionMonths { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.InternalClientActivityConfigureRequest"/> and sets the default values.
        /// </summary>
        public InternalClientActivityConfigureRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Enabled = "default";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.InternalClientActivityConfigureRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.InternalClientActivityConfigureRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.InternalClientActivityConfigureRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_report_months", n => { DefaultReportMonths = n.GetIntValue(); } },
                { "enabled", n => { Enabled = n.GetStringValue(); } },
                { "retention_months", n => { RetentionMonths = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("default_report_months", DefaultReportMonths);
            writer.WriteStringValue("enabled", Enabled);
            writer.WriteIntValue("retention_months", RetentionMonths);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
