// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InternalClientActivityReportCountsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of usage counts broken down by namespace. Each element is an object containing namespace name, counts, and mounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_by_namespace>? ByNamespace { get; set; }
#nullable restore
#else
        public List<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_by_namespace> ByNamespace { get; set; }
#endif
        /// <summary>The end time of the query interval.</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>A list of objects, each representing monthly client count data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_months>? Months { get; set; }
#nullable restore
#else
        public List<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_months> Months { get; set; }
#endif
        /// <summary>The start time of the query interval.</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>Aggregated usage counts across all namespaces.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_total? Total { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_total Total { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse"/> and sets the default values.
        /// </summary>
        public InternalClientActivityReportCountsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "by_namespace", n => { ByNamespace = n.GetCollectionOfObjectValues<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_by_namespace>(global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_by_namespace.CreateFromDiscriminatorValue)?.AsList(); } },
                { "end_time", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "months", n => { Months = n.GetCollectionOfObjectValues<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_months>(global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_months.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_time", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "total", n => { Total = n.GetObjectValue<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_total>(global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_total.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_by_namespace>("by_namespace", ByNamespace);
            writer.WriteDateTimeOffsetValue("end_time", EndTime);
            writer.WriteCollectionOfObjectValues<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_months>("months", Months);
            writer.WriteDateTimeOffsetValue("start_time", StartTime);
            writer.WriteObjectValue<global::VaultApi.Client.Models.InternalClientActivityReportCountsResponse_total>("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
