// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class JwtWriteRoleRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The metadata to be tied to generated entity alias. This should be a list or map containing the metadata in key value pairs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.JwtWriteRoleRequest_alias_metadata? AliasMetadata { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.JwtWriteRoleRequest_alias_metadata AliasMetadata { get; set; }
#endif
        /// <summary>Comma-separated list of allowed values for redirect_uri</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedRedirectUris { get; set; }
#nullable restore
#else
        public List<string> AllowedRedirectUris { get; set; }
#endif
        /// <summary>Comma-separated list of &apos;aud&apos; claims that are valid for login; any match is sufficient</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BoundAudiences { get; set; }
#nullable restore
#else
        public List<string> BoundAudiences { get; set; }
#endif
        /// <summary>Use &quot;token_bound_cidrs&quot; instead. If this and &quot;token_bound_cidrs&quot; are both specified, only &quot;token_bound_cidrs&quot; will be used.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BoundCidrs { get; set; }
#nullable restore
#else
        public List<string> BoundCidrs { get; set; }
#endif
        /// <summary>Map of claims/values which must match for login</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.JwtWriteRoleRequest_bound_claims? BoundClaims { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.JwtWriteRoleRequest_bound_claims BoundClaims { get; set; }
#endif
        /// <summary>How to interpret values in the map of claims/values (which must match for login): allowed values are &apos;string&apos; or &apos;glob&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BoundClaimsType { get; set; }
#nullable restore
#else
        public string BoundClaimsType { get; set; }
#endif
        /// <summary>The &apos;sub&apos; claim that is valid for login. Optional.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BoundSubject { get; set; }
#nullable restore
#else
        public string BoundSubject { get; set; }
#endif
        /// <summary>Mappings of claims (key) that will be copied to a metadata field (value)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.JwtWriteRoleRequest_claim_mappings? ClaimMappings { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.JwtWriteRoleRequest_claim_mappings ClaimMappings { get; set; }
#endif
        /// <summary>Duration in seconds of leeway when validating all claims to account for clock skew. Defaults to 60 (1 minute) if set to 0 and can be disabled if set to -1.</summary>
        public TimeSpan? ClockSkewLeeway { get; set; }
        /// <summary>Duration in seconds of leeway when validating expiration of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1.</summary>
        public TimeSpan? ExpirationLeeway { get; set; }
        /// <summary>The claim to use for the Identity group alias names</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupsClaim { get; set; }
#nullable restore
#else
        public string GroupsClaim { get; set; }
#endif
        /// <summary>Specifies the allowable elapsed time in seconds since the last time the user was actively authenticated.</summary>
        public TimeSpan? MaxAge { get; set; }
        /// <summary>Use &quot;token_max_ttl&quot; instead. If this and &quot;token_max_ttl&quot; are both specified, only &quot;token_max_ttl&quot; will be used.</summary>
        [Obsolete("")]
        public TimeSpan? MaxTtl { get; set; }
        /// <summary>Duration in seconds of leeway when validating not before values of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1.</summary>
        public TimeSpan? NotBeforeLeeway { get; set; }
        /// <summary>Use &quot;token_num_uses&quot; instead. If this and &quot;token_num_uses&quot; are both specified, only &quot;token_num_uses&quot; will be used.</summary>
        [Obsolete("")]
        public int? NumUses { get; set; }
        /// <summary>Comma-separated list of OIDC scopes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OidcScopes { get; set; }
#nullable restore
#else
        public List<string> OidcScopes { get; set; }
#endif
        /// <summary>Use &quot;token_period&quot; instead. If this and &quot;token_period&quot; are both specified, only &quot;token_period&quot; will be used.</summary>
        [Obsolete("")]
        public TimeSpan? Period { get; set; }
        /// <summary>Use &quot;token_policies&quot; instead. If this and &quot;token_policies&quot; are both specified, only &quot;token_policies&quot; will be used.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Policies { get; set; }
#nullable restore
#else
        public List<string> Policies { get; set; }
#endif
        /// <summary>Type of the role, either &apos;jwt&apos; or &apos;oidc&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoleType { get; set; }
#nullable restore
#else
        public string RoleType { get; set; }
#endif
        /// <summary>Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TokenBoundCidrs { get; set; }
#nullable restore
#else
        public List<string> TokenBoundCidrs { get; set; }
#endif
        /// <summary>If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.</summary>
        public TimeSpan? TokenExplicitMaxTtl { get; set; }
        /// <summary>The maximum lifetime of the generated token</summary>
        public TimeSpan? TokenMaxTtl { get; set; }
        /// <summary>If true, the &apos;default&apos; policy will not automatically be added to generated tokens</summary>
        public bool? TokenNoDefaultPolicy { get; set; }
        /// <summary>The maximum number of times a token may be used, a value of zero means unlimited</summary>
        public int? TokenNumUses { get; set; }
        /// <summary>If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. &quot;24h&quot;).</summary>
        public TimeSpan? TokenPeriod { get; set; }
        /// <summary>Comma-separated list of policies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TokenPolicies { get; set; }
#nullable restore
#else
        public List<string> TokenPolicies { get; set; }
#endif
        /// <summary>The initial ttl of the token to generate</summary>
        public TimeSpan? TokenTtl { get; set; }
        /// <summary>The type of token to generate, service or batch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenType { get; set; }
#nullable restore
#else
        public string TokenType { get; set; }
#endif
        /// <summary>Use &quot;token_ttl&quot; instead. If this and &quot;token_ttl&quot; are both specified, only &quot;token_ttl&quot; will be used.</summary>
        [Obsolete("")]
        public TimeSpan? Ttl { get; set; }
        /// <summary>The claim to use for the Identity entity alias name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserClaim { get; set; }
#nullable restore
#else
        public string UserClaim { get; set; }
#endif
        /// <summary>If true, the user_claim value will use JSON pointer syntax for referencing claims.</summary>
        public bool? UserClaimJsonPointer { get; set; }
        /// <summary>Log received OIDC tokens and claims when debug-level logging is active. Not recommended in production since sensitive information may be present in OIDC responses.</summary>
        public bool? VerboseOidcLogging { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.JwtWriteRoleRequest"/> and sets the default values.
        /// </summary>
        public JwtWriteRoleRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            BoundClaimsType = "string";
            TokenType = "default-service";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.JwtWriteRoleRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.JwtWriteRoleRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.JwtWriteRoleRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias_metadata", n => { AliasMetadata = n.GetObjectValue<global::VaultApi.Client.Models.JwtWriteRoleRequest_alias_metadata>(global::VaultApi.Client.Models.JwtWriteRoleRequest_alias_metadata.CreateFromDiscriminatorValue); } },
                { "allowed_redirect_uris", n => { AllowedRedirectUris = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "bound_audiences", n => { BoundAudiences = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "bound_cidrs", n => { BoundCidrs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "bound_claims", n => { BoundClaims = n.GetObjectValue<global::VaultApi.Client.Models.JwtWriteRoleRequest_bound_claims>(global::VaultApi.Client.Models.JwtWriteRoleRequest_bound_claims.CreateFromDiscriminatorValue); } },
                { "bound_claims_type", n => { BoundClaimsType = n.GetStringValue(); } },
                { "bound_subject", n => { BoundSubject = n.GetStringValue(); } },
                { "claim_mappings", n => { ClaimMappings = n.GetObjectValue<global::VaultApi.Client.Models.JwtWriteRoleRequest_claim_mappings>(global::VaultApi.Client.Models.JwtWriteRoleRequest_claim_mappings.CreateFromDiscriminatorValue); } },
                { "clock_skew_leeway", n => { ClockSkewLeeway = n.GetTimeSpanValue(); } },
                { "expiration_leeway", n => { ExpirationLeeway = n.GetTimeSpanValue(); } },
                { "groups_claim", n => { GroupsClaim = n.GetStringValue(); } },
                { "max_age", n => { MaxAge = n.GetTimeSpanValue(); } },
                { "max_ttl", n => { MaxTtl = n.GetTimeSpanValue(); } },
                { "not_before_leeway", n => { NotBeforeLeeway = n.GetTimeSpanValue(); } },
                { "num_uses", n => { NumUses = n.GetIntValue(); } },
                { "oidc_scopes", n => { OidcScopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "period", n => { Period = n.GetTimeSpanValue(); } },
                { "policies", n => { Policies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "role_type", n => { RoleType = n.GetStringValue(); } },
                { "token_bound_cidrs", n => { TokenBoundCidrs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "token_explicit_max_ttl", n => { TokenExplicitMaxTtl = n.GetTimeSpanValue(); } },
                { "token_max_ttl", n => { TokenMaxTtl = n.GetTimeSpanValue(); } },
                { "token_no_default_policy", n => { TokenNoDefaultPolicy = n.GetBoolValue(); } },
                { "token_num_uses", n => { TokenNumUses = n.GetIntValue(); } },
                { "token_period", n => { TokenPeriod = n.GetTimeSpanValue(); } },
                { "token_policies", n => { TokenPolicies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "token_ttl", n => { TokenTtl = n.GetTimeSpanValue(); } },
                { "token_type", n => { TokenType = n.GetStringValue(); } },
                { "ttl", n => { Ttl = n.GetTimeSpanValue(); } },
                { "user_claim", n => { UserClaim = n.GetStringValue(); } },
                { "user_claim_json_pointer", n => { UserClaimJsonPointer = n.GetBoolValue(); } },
                { "verbose_oidc_logging", n => { VerboseOidcLogging = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VaultApi.Client.Models.JwtWriteRoleRequest_alias_metadata>("alias_metadata", AliasMetadata);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_redirect_uris", AllowedRedirectUris);
            writer.WriteCollectionOfPrimitiveValues<string>("bound_audiences", BoundAudiences);
            writer.WriteCollectionOfPrimitiveValues<string>("bound_cidrs", BoundCidrs);
            writer.WriteObjectValue<global::VaultApi.Client.Models.JwtWriteRoleRequest_bound_claims>("bound_claims", BoundClaims);
            writer.WriteStringValue("bound_claims_type", BoundClaimsType);
            writer.WriteStringValue("bound_subject", BoundSubject);
            writer.WriteObjectValue<global::VaultApi.Client.Models.JwtWriteRoleRequest_claim_mappings>("claim_mappings", ClaimMappings);
            writer.WriteTimeSpanValue("clock_skew_leeway", ClockSkewLeeway);
            writer.WriteTimeSpanValue("expiration_leeway", ExpirationLeeway);
            writer.WriteStringValue("groups_claim", GroupsClaim);
            writer.WriteTimeSpanValue("max_age", MaxAge);
            writer.WriteTimeSpanValue("max_ttl", MaxTtl);
            writer.WriteTimeSpanValue("not_before_leeway", NotBeforeLeeway);
            writer.WriteIntValue("num_uses", NumUses);
            writer.WriteCollectionOfPrimitiveValues<string>("oidc_scopes", OidcScopes);
            writer.WriteTimeSpanValue("period", Period);
            writer.WriteCollectionOfPrimitiveValues<string>("policies", Policies);
            writer.WriteStringValue("role_type", RoleType);
            writer.WriteCollectionOfPrimitiveValues<string>("token_bound_cidrs", TokenBoundCidrs);
            writer.WriteTimeSpanValue("token_explicit_max_ttl", TokenExplicitMaxTtl);
            writer.WriteTimeSpanValue("token_max_ttl", TokenMaxTtl);
            writer.WriteBoolValue("token_no_default_policy", TokenNoDefaultPolicy);
            writer.WriteIntValue("token_num_uses", TokenNumUses);
            writer.WriteTimeSpanValue("token_period", TokenPeriod);
            writer.WriteCollectionOfPrimitiveValues<string>("token_policies", TokenPolicies);
            writer.WriteTimeSpanValue("token_ttl", TokenTtl);
            writer.WriteStringValue("token_type", TokenType);
            writer.WriteTimeSpanValue("ttl", Ttl);
            writer.WriteStringValue("user_claim", UserClaim);
            writer.WriteBoolValue("user_claim_json_pointer", UserClaimJsonPointer);
            writer.WriteBoolValue("verbose_oidc_logging", VerboseOidcLogging);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
