// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KvV2WriteResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_time property</summary>
        public DateTimeOffset? CreatedTime { get; set; }
        /// <summary>The custom_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.KvV2WriteResponse_custom_metadata? CustomMetadata { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.KvV2WriteResponse_custom_metadata CustomMetadata { get; set; }
#endif
        /// <summary>The deletion_time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeletionTime { get; set; }
#nullable restore
#else
        public string DeletionTime { get; set; }
#endif
        /// <summary>The destroyed property</summary>
        public bool? Destroyed { get; set; }
        /// <summary>The version property</summary>
        public long? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.KvV2WriteResponse"/> and sets the default values.
        /// </summary>
        public KvV2WriteResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.KvV2WriteResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.KvV2WriteResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.KvV2WriteResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_time", n => { CreatedTime = n.GetDateTimeOffsetValue(); } },
                { "custom_metadata", n => { CustomMetadata = n.GetObjectValue<global::VaultApi.Client.Models.KvV2WriteResponse_custom_metadata>(global::VaultApi.Client.Models.KvV2WriteResponse_custom_metadata.CreateFromDiscriminatorValue); } },
                { "deletion_time", n => { DeletionTime = n.GetStringValue(); } },
                { "destroyed", n => { Destroyed = n.GetBoolValue(); } },
                { "version", n => { Version = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_time", CreatedTime);
            writer.WriteObjectValue<global::VaultApi.Client.Models.KvV2WriteResponse_custom_metadata>("custom_metadata", CustomMetadata);
            writer.WriteStringValue("deletion_time", DeletionTime);
            writer.WriteBoolValue("destroyed", Destroyed);
            writer.WriteLongValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
