// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KvV2PatchRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contents of the data map will be stored and returned on read.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.KvV2PatchRequest_data? Data { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.KvV2PatchRequest_data Data { get; set; }
#endif
        /// <summary>Options for writing a KV entry. Set the &quot;cas&quot; value to use a Check-And-Set operation. If not set the write will be allowed. If set to 0 a write will only be allowed if the key doesn’t exist. If the index is non-zero the write will only be allowed if the key’s current version matches the version specified in the cas parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.KvV2PatchRequest_options? Options { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.KvV2PatchRequest_options Options { get; set; }
#endif
        /// <summary>If provided during a read, the value at the version number will be returned</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.KvV2PatchRequest"/> and sets the default values.
        /// </summary>
        public KvV2PatchRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.KvV2PatchRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.KvV2PatchRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.KvV2PatchRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::VaultApi.Client.Models.KvV2PatchRequest_data>(global::VaultApi.Client.Models.KvV2PatchRequest_data.CreateFromDiscriminatorValue); } },
                { "options", n => { Options = n.GetObjectValue<global::VaultApi.Client.Models.KvV2PatchRequest_options>(global::VaultApi.Client.Models.KvV2PatchRequest_options.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VaultApi.Client.Models.KvV2PatchRequest_data>("data", Data);
            writer.WriteObjectValue<global::VaultApi.Client.Models.KvV2PatchRequest_options>("options", Options);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
