// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KvV2ReadMetadataResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cas_required property</summary>
        public bool? CasRequired { get; set; }
        /// <summary>The created_time property</summary>
        public DateTimeOffset? CreatedTime { get; set; }
        /// <summary>The current_version property</summary>
        public long? CurrentVersion { get; set; }
        /// <summary>User-provided key-value pairs that are used to describe arbitrary and version-agnostic information about a secret.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.KvV2ReadMetadataResponse_custom_metadata? CustomMetadata { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.KvV2ReadMetadataResponse_custom_metadata CustomMetadata { get; set; }
#endif
        /// <summary>The length of time before a version is deleted.</summary>
        public TimeSpan? DeleteVersionAfter { get; set; }
        /// <summary>Attribution information of the last actor to update this secret</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.KvV2ReadMetadataResponse_last_updated_by? LastUpdatedBy { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.KvV2ReadMetadataResponse_last_updated_by LastUpdatedBy { get; set; }
#endif
        /// <summary>The number of versions to keep</summary>
        public long? MaxVersions { get; set; }
        /// <summary>The oldest_version property</summary>
        public long? OldestVersion { get; set; }
        /// <summary>The updated_time property</summary>
        public DateTimeOffset? UpdatedTime { get; set; }
        /// <summary>The versions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.KvV2ReadMetadataResponse_versions? Versions { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.KvV2ReadMetadataResponse_versions Versions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.KvV2ReadMetadataResponse"/> and sets the default values.
        /// </summary>
        public KvV2ReadMetadataResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.KvV2ReadMetadataResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.KvV2ReadMetadataResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.KvV2ReadMetadataResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cas_required", n => { CasRequired = n.GetBoolValue(); } },
                { "created_time", n => { CreatedTime = n.GetDateTimeOffsetValue(); } },
                { "current_version", n => { CurrentVersion = n.GetLongValue(); } },
                { "custom_metadata", n => { CustomMetadata = n.GetObjectValue<global::VaultApi.Client.Models.KvV2ReadMetadataResponse_custom_metadata>(global::VaultApi.Client.Models.KvV2ReadMetadataResponse_custom_metadata.CreateFromDiscriminatorValue); } },
                { "delete_version_after", n => { DeleteVersionAfter = n.GetTimeSpanValue(); } },
                { "last_updated_by", n => { LastUpdatedBy = n.GetObjectValue<global::VaultApi.Client.Models.KvV2ReadMetadataResponse_last_updated_by>(global::VaultApi.Client.Models.KvV2ReadMetadataResponse_last_updated_by.CreateFromDiscriminatorValue); } },
                { "max_versions", n => { MaxVersions = n.GetLongValue(); } },
                { "oldest_version", n => { OldestVersion = n.GetLongValue(); } },
                { "updated_time", n => { UpdatedTime = n.GetDateTimeOffsetValue(); } },
                { "versions", n => { Versions = n.GetObjectValue<global::VaultApi.Client.Models.KvV2ReadMetadataResponse_versions>(global::VaultApi.Client.Models.KvV2ReadMetadataResponse_versions.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cas_required", CasRequired);
            writer.WriteDateTimeOffsetValue("created_time", CreatedTime);
            writer.WriteLongValue("current_version", CurrentVersion);
            writer.WriteObjectValue<global::VaultApi.Client.Models.KvV2ReadMetadataResponse_custom_metadata>("custom_metadata", CustomMetadata);
            writer.WriteTimeSpanValue("delete_version_after", DeleteVersionAfter);
            writer.WriteObjectValue<global::VaultApi.Client.Models.KvV2ReadMetadataResponse_last_updated_by>("last_updated_by", LastUpdatedBy);
            writer.WriteLongValue("max_versions", MaxVersions);
            writer.WriteLongValue("oldest_version", OldestVersion);
            writer.WriteDateTimeOffsetValue("updated_time", UpdatedTime);
            writer.WriteObjectValue<global::VaultApi.Client.Models.KvV2ReadMetadataResponse_versions>("versions", Versions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
