// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LeaderStatusResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active_time property</summary>
        public DateTimeOffset? ActiveTime { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ha_enabled property</summary>
        public bool? HaEnabled { get; set; }
        /// <summary>The is_self property</summary>
        public bool? IsSelf { get; set; }
        /// <summary>The last_wal property</summary>
        public long? LastWal { get; set; }
        /// <summary>The leader_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeaderAddress { get; set; }
#nullable restore
#else
        public string LeaderAddress { get; set; }
#endif
        /// <summary>The leader_cluster_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeaderClusterAddress { get; set; }
#nullable restore
#else
        public string LeaderClusterAddress { get; set; }
#endif
        /// <summary>The performance_standby property</summary>
        public bool? PerformanceStandby { get; set; }
        /// <summary>The performance_standby_last_remote_wal property</summary>
        public long? PerformanceStandbyLastRemoteWal { get; set; }
        /// <summary>The raft_applied_index property</summary>
        public long? RaftAppliedIndex { get; set; }
        /// <summary>The raft_committed_index property</summary>
        public long? RaftCommittedIndex { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.LeaderStatusResponse"/> and sets the default values.
        /// </summary>
        public LeaderStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.LeaderStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.LeaderStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.LeaderStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_time", n => { ActiveTime = n.GetDateTimeOffsetValue(); } },
                { "ha_enabled", n => { HaEnabled = n.GetBoolValue(); } },
                { "is_self", n => { IsSelf = n.GetBoolValue(); } },
                { "last_wal", n => { LastWal = n.GetLongValue(); } },
                { "leader_address", n => { LeaderAddress = n.GetStringValue(); } },
                { "leader_cluster_address", n => { LeaderClusterAddress = n.GetStringValue(); } },
                { "performance_standby", n => { PerformanceStandby = n.GetBoolValue(); } },
                { "performance_standby_last_remote_wal", n => { PerformanceStandbyLastRemoteWal = n.GetLongValue(); } },
                { "raft_applied_index", n => { RaftAppliedIndex = n.GetLongValue(); } },
                { "raft_committed_index", n => { RaftCommittedIndex = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("active_time", ActiveTime);
            writer.WriteBoolValue("ha_enabled", HaEnabled);
            writer.WriteBoolValue("is_self", IsSelf);
            writer.WriteLongValue("last_wal", LastWal);
            writer.WriteStringValue("leader_address", LeaderAddress);
            writer.WriteStringValue("leader_cluster_address", LeaderClusterAddress);
            writer.WriteBoolValue("performance_standby", PerformanceStandby);
            writer.WriteLongValue("performance_standby_last_remote_wal", PerformanceStandbyLastRemoteWal);
            writer.WriteLongValue("raft_applied_index", RaftAppliedIndex);
            writer.WriteLongValue("raft_committed_index", RaftCommittedIndex);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
