// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MfaCreateDuoMethodRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>API host name for Duo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiHostname { get; set; }
#nullable restore
#else
        public string ApiHostname { get; set; }
#endif
        /// <summary>Integration key for Duo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationKey { get; set; }
#nullable restore
#else
        public string IntegrationKey { get; set; }
#endif
        /// <summary>The unique name identifier for this MFA method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MethodName { get; set; }
#nullable restore
#else
        public string MethodName { get; set; }
#endif
        /// <summary>Push information for Duo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PushInfo { get; set; }
#nullable restore
#else
        public string PushInfo { get; set; }
#endif
        /// <summary>Secret key for Duo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecretKey { get; set; }
#nullable restore
#else
        public string SecretKey { get; set; }
#endif
        /// <summary>If true, the user is reminded to use the passcode upon MFA validation. This option does not enforce using the passcode. Defaults to false.</summary>
        public bool? UsePasscode { get; set; }
        /// <summary>A template string for mapping Identity names to MFA method names. Values to subtitute should be placed in {{}}. For example, &quot;{{alias.name}}@example.com&quot;. Currently-supported mappings: alias.name: The name returned by the mount configured via the mount_accessor parameter If blank, the Alias&apos;s name field will be used as-is.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsernameFormat { get; set; }
#nullable restore
#else
        public string UsernameFormat { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.MfaCreateDuoMethodRequest"/> and sets the default values.
        /// </summary>
        public MfaCreateDuoMethodRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.MfaCreateDuoMethodRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.MfaCreateDuoMethodRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.MfaCreateDuoMethodRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_hostname", n => { ApiHostname = n.GetStringValue(); } },
                { "integration_key", n => { IntegrationKey = n.GetStringValue(); } },
                { "method_name", n => { MethodName = n.GetStringValue(); } },
                { "push_info", n => { PushInfo = n.GetStringValue(); } },
                { "secret_key", n => { SecretKey = n.GetStringValue(); } },
                { "use_passcode", n => { UsePasscode = n.GetBoolValue(); } },
                { "username_format", n => { UsernameFormat = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_hostname", ApiHostname);
            writer.WriteStringValue("integration_key", IntegrationKey);
            writer.WriteStringValue("method_name", MethodName);
            writer.WriteStringValue("push_info", PushInfo);
            writer.WriteStringValue("secret_key", SecretKey);
            writer.WriteBoolValue("use_passcode", UsePasscode);
            writer.WriteStringValue("username_format", UsernameFormat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
