// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MfaUpdateOktaMethodRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Okta API key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiToken { get; set; }
#nullable restore
#else
        public string ApiToken { get; set; }
#endif
        /// <summary>The base domain to use for the Okta API. When not specified in the configuration, &quot;okta.com&quot; is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseUrl { get; set; }
#nullable restore
#else
        public string BaseUrl { get; set; }
#endif
        /// <summary>The unique name identifier for this MFA method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MethodName { get; set; }
#nullable restore
#else
        public string MethodName { get; set; }
#endif
        /// <summary>Name of the organization to be used in the Okta API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgName { get; set; }
#nullable restore
#else
        public string OrgName { get; set; }
#endif
        /// <summary>If true, the username will only match the primary email for the account. Defaults to false.</summary>
        public bool? PrimaryEmail { get; set; }
        /// <summary>(DEPRECATED) Use base_url instead.</summary>
        public bool? Production { get; set; }
        /// <summary>A template string for mapping Identity names to MFA method names. Values to substitute should be placed in {{}}. For example, &quot;{{entity.name}}@example.com&quot;. If blank, the Entity&apos;s name field will be used as-is.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsernameFormat { get; set; }
#nullable restore
#else
        public string UsernameFormat { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.MfaUpdateOktaMethodRequest"/> and sets the default values.
        /// </summary>
        public MfaUpdateOktaMethodRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.MfaUpdateOktaMethodRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.MfaUpdateOktaMethodRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.MfaUpdateOktaMethodRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_token", n => { ApiToken = n.GetStringValue(); } },
                { "base_url", n => { BaseUrl = n.GetStringValue(); } },
                { "method_name", n => { MethodName = n.GetStringValue(); } },
                { "org_name", n => { OrgName = n.GetStringValue(); } },
                { "primary_email", n => { PrimaryEmail = n.GetBoolValue(); } },
                { "production", n => { Production = n.GetBoolValue(); } },
                { "username_format", n => { UsernameFormat = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_token", ApiToken);
            writer.WriteStringValue("base_url", BaseUrl);
            writer.WriteStringValue("method_name", MethodName);
            writer.WriteStringValue("org_name", OrgName);
            writer.WriteBoolValue("primary_email", PrimaryEmail);
            writer.WriteBoolValue("production", Production);
            writer.WriteStringValue("username_format", UsernameFormat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
