// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MountsTuneConfigurationParametersRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowed_managed_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedManagedKeys { get; set; }
#nullable restore
#else
        public List<string> AllowedManagedKeys { get; set; }
#endif
        /// <summary>A list of headers to whitelist and allow a plugin to set on responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedResponseHeaders { get; set; }
#nullable restore
#else
        public List<string> AllowedResponseHeaders { get; set; }
#endif
        /// <summary>The list of keys in the request data object that will not be HMAC&apos;d by audit devices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AuditNonHmacRequestKeys { get; set; }
#nullable restore
#else
        public List<string> AuditNonHmacRequestKeys { get; set; }
#endif
        /// <summary>The list of keys in the response data object that will not be HMAC&apos;d by audit devices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AuditNonHmacResponseKeys { get; set; }
#nullable restore
#else
        public List<string> AuditNonHmacResponseKeys { get; set; }
#endif
        /// <summary>The default lease TTL for this mount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultLeaseTtl { get; set; }
#nullable restore
#else
        public string DefaultLeaseTtl { get; set; }
#endif
        /// <summary>The delegated_auth_accessors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DelegatedAuthAccessors { get; set; }
#nullable restore
#else
        public List<string> DelegatedAuthAccessors { get; set; }
#endif
        /// <summary>User-friendly description for this credential backend.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The name of the key used to sign plugin identity tokens. Defaults to the default key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentityTokenKey { get; set; }
#nullable restore
#else
        public string IdentityTokenKey { get; set; }
#endif
        /// <summary>Determines the visibility of the mount in the UI-specific listing endpoint. Accepted value are &apos;unauth&apos; and &apos;hidden&apos;, with the empty default (&apos;&apos;) behaving like &apos;hidden&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListingVisibility { get; set; }
#nullable restore
#else
        public string ListingVisibility { get; set; }
#endif
        /// <summary>The max lease TTL for this mount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxLeaseTtl { get; set; }
#nullable restore
#else
        public string MaxLeaseTtl { get; set; }
#endif
        /// <summary>The options to pass into the backend. Should be a json object with string keys and values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_options? Options { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_options Options { get; set; }
#endif
        /// <summary>A list of headers to whitelist and pass from the request to the plugin.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PassthroughRequestHeaders { get; set; }
#nullable restore
#else
        public List<string> PassthroughRequestHeaders { get; set; }
#endif
        /// <summary>The semantic version of the plugin to use, or image tag if oci_image is provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PluginVersion { get; set; }
#nullable restore
#else
        public string PluginVersion { get; set; }
#endif
        /// <summary>The type of token to issue (service or batch).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenType { get; set; }
#nullable restore
#else
        public string TokenType { get; set; }
#endif
        /// <summary>Whether to trim a trailing slash on incoming requests to this mount</summary>
        public bool? TrimRequestTrailingSlashes { get; set; }
        /// <summary>The user lockout configuration to pass into the backend. Should be a json object with string keys and values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_user_lockout_config? UserLockoutConfig { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_user_lockout_config UserLockoutConfig { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest"/> and sets the default values.
        /// </summary>
        public MountsTuneConfigurationParametersRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_managed_keys", n => { AllowedManagedKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowed_response_headers", n => { AllowedResponseHeaders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "audit_non_hmac_request_keys", n => { AuditNonHmacRequestKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "audit_non_hmac_response_keys", n => { AuditNonHmacResponseKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "default_lease_ttl", n => { DefaultLeaseTtl = n.GetStringValue(); } },
                { "delegated_auth_accessors", n => { DelegatedAuthAccessors = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "identity_token_key", n => { IdentityTokenKey = n.GetStringValue(); } },
                { "listing_visibility", n => { ListingVisibility = n.GetStringValue(); } },
                { "max_lease_ttl", n => { MaxLeaseTtl = n.GetStringValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_options>(global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_options.CreateFromDiscriminatorValue); } },
                { "passthrough_request_headers", n => { PassthroughRequestHeaders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "plugin_version", n => { PluginVersion = n.GetStringValue(); } },
                { "token_type", n => { TokenType = n.GetStringValue(); } },
                { "trim_request_trailing_slashes", n => { TrimRequestTrailingSlashes = n.GetBoolValue(); } },
                { "user_lockout_config", n => { UserLockoutConfig = n.GetObjectValue<global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_user_lockout_config>(global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_user_lockout_config.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_managed_keys", AllowedManagedKeys);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_response_headers", AllowedResponseHeaders);
            writer.WriteCollectionOfPrimitiveValues<string>("audit_non_hmac_request_keys", AuditNonHmacRequestKeys);
            writer.WriteCollectionOfPrimitiveValues<string>("audit_non_hmac_response_keys", AuditNonHmacResponseKeys);
            writer.WriteStringValue("default_lease_ttl", DefaultLeaseTtl);
            writer.WriteCollectionOfPrimitiveValues<string>("delegated_auth_accessors", DelegatedAuthAccessors);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("identity_token_key", IdentityTokenKey);
            writer.WriteStringValue("listing_visibility", ListingVisibility);
            writer.WriteStringValue("max_lease_ttl", MaxLeaseTtl);
            writer.WriteObjectValue<global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_options>("options", Options);
            writer.WriteCollectionOfPrimitiveValues<string>("passthrough_request_headers", PassthroughRequestHeaders);
            writer.WriteStringValue("plugin_version", PluginVersion);
            writer.WriteStringValue("token_type", TokenType);
            writer.WriteBoolValue("trim_request_trailing_slashes", TrimRequestTrailingSlashes);
            writer.WriteObjectValue<global::VaultApi.Client.Models.MountsTuneConfigurationParametersRequest_user_lockout_config>("user_lockout_config", UserLockoutConfig);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
