// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MountsAuthReadTuningInformationResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowed_managed_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedManagedKeys { get; set; }
#nullable restore
#else
        public List<string> AllowedManagedKeys { get; set; }
#endif
        /// <summary>The allowed_response_headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedResponseHeaders { get; set; }
#nullable restore
#else
        public List<string> AllowedResponseHeaders { get; set; }
#endif
        /// <summary>The audit_non_hmac_request_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AuditNonHmacRequestKeys { get; set; }
#nullable restore
#else
        public List<string> AuditNonHmacRequestKeys { get; set; }
#endif
        /// <summary>The audit_non_hmac_response_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AuditNonHmacResponseKeys { get; set; }
#nullable restore
#else
        public List<string> AuditNonHmacResponseKeys { get; set; }
#endif
        /// <summary>The default_lease_ttl property</summary>
        public int? DefaultLeaseTtl { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The external_entropy_access property</summary>
        public bool? ExternalEntropyAccess { get; set; }
        /// <summary>The force_no_cache property</summary>
        public bool? ForceNoCache { get; set; }
        /// <summary>The identity_token_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentityTokenKey { get; set; }
#nullable restore
#else
        public string IdentityTokenKey { get; set; }
#endif
        /// <summary>The listing_visibility property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListingVisibility { get; set; }
#nullable restore
#else
        public string ListingVisibility { get; set; }
#endif
        /// <summary>The max_lease_ttl property</summary>
        public int? MaxLeaseTtl { get; set; }
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse_options? Options { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse_options Options { get; set; }
#endif
        /// <summary>The passthrough_request_headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PassthroughRequestHeaders { get; set; }
#nullable restore
#else
        public List<string> PassthroughRequestHeaders { get; set; }
#endif
        /// <summary>The plugin_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PluginVersion { get; set; }
#nullable restore
#else
        public string PluginVersion { get; set; }
#endif
        /// <summary>The token_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenType { get; set; }
#nullable restore
#else
        public string TokenType { get; set; }
#endif
        /// <summary>The trim_request_trailing_slashes property</summary>
        public bool? TrimRequestTrailingSlashes { get; set; }
        /// <summary>The user_lockout_counter_reset_duration property</summary>
        public long? UserLockoutCounterResetDuration { get; set; }
        /// <summary>The user_lockout_disable property</summary>
        public bool? UserLockoutDisable { get; set; }
        /// <summary>The user_lockout_duration property</summary>
        public long? UserLockoutDuration { get; set; }
        /// <summary>The user_lockout_threshold property</summary>
        public long? UserLockoutThreshold { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse"/> and sets the default values.
        /// </summary>
        public MountsAuthReadTuningInformationResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_managed_keys", n => { AllowedManagedKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowed_response_headers", n => { AllowedResponseHeaders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "audit_non_hmac_request_keys", n => { AuditNonHmacRequestKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "audit_non_hmac_response_keys", n => { AuditNonHmacResponseKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "default_lease_ttl", n => { DefaultLeaseTtl = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "external_entropy_access", n => { ExternalEntropyAccess = n.GetBoolValue(); } },
                { "force_no_cache", n => { ForceNoCache = n.GetBoolValue(); } },
                { "identity_token_key", n => { IdentityTokenKey = n.GetStringValue(); } },
                { "listing_visibility", n => { ListingVisibility = n.GetStringValue(); } },
                { "max_lease_ttl", n => { MaxLeaseTtl = n.GetIntValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse_options>(global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse_options.CreateFromDiscriminatorValue); } },
                { "passthrough_request_headers", n => { PassthroughRequestHeaders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "plugin_version", n => { PluginVersion = n.GetStringValue(); } },
                { "token_type", n => { TokenType = n.GetStringValue(); } },
                { "trim_request_trailing_slashes", n => { TrimRequestTrailingSlashes = n.GetBoolValue(); } },
                { "user_lockout_counter_reset_duration", n => { UserLockoutCounterResetDuration = n.GetLongValue(); } },
                { "user_lockout_disable", n => { UserLockoutDisable = n.GetBoolValue(); } },
                { "user_lockout_duration", n => { UserLockoutDuration = n.GetLongValue(); } },
                { "user_lockout_threshold", n => { UserLockoutThreshold = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_managed_keys", AllowedManagedKeys);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_response_headers", AllowedResponseHeaders);
            writer.WriteCollectionOfPrimitiveValues<string>("audit_non_hmac_request_keys", AuditNonHmacRequestKeys);
            writer.WriteCollectionOfPrimitiveValues<string>("audit_non_hmac_response_keys", AuditNonHmacResponseKeys);
            writer.WriteIntValue("default_lease_ttl", DefaultLeaseTtl);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("external_entropy_access", ExternalEntropyAccess);
            writer.WriteBoolValue("force_no_cache", ForceNoCache);
            writer.WriteStringValue("identity_token_key", IdentityTokenKey);
            writer.WriteStringValue("listing_visibility", ListingVisibility);
            writer.WriteIntValue("max_lease_ttl", MaxLeaseTtl);
            writer.WriteObjectValue<global::VaultApi.Client.Models.MountsAuthReadTuningInformationResponse_options>("options", Options);
            writer.WriteCollectionOfPrimitiveValues<string>("passthrough_request_headers", PassthroughRequestHeaders);
            writer.WriteStringValue("plugin_version", PluginVersion);
            writer.WriteStringValue("token_type", TokenType);
            writer.WriteBoolValue("trim_request_trailing_slashes", TrimRequestTrailingSlashes);
            writer.WriteLongValue("user_lockout_counter_reset_duration", UserLockoutCounterResetDuration);
            writer.WriteBoolValue("user_lockout_disable", UserLockoutDisable);
            writer.WriteLongValue("user_lockout_duration", UserLockoutDuration);
            writer.WriteLongValue("user_lockout_threshold", UserLockoutThreshold);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
