// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RateLimitQuotasConfigureRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Specifies the list of exempt global paths from all rate limit quotas. If empty no global paths will be exempt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AbsoluteRateLimitExemptPaths { get; set; }
#nullable restore
#else
        public List<string> AbsoluteRateLimitExemptPaths { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If set, starts audit logging of requests that get rejected due to rate limit quota rule violations.</summary>
        public bool? EnableRateLimitAuditLogging { get; set; }
        /// <summary>If set, additional rate limit quota HTTP headers will be added to responses.</summary>
        public bool? EnableRateLimitResponseHeaders { get; set; }
        /// <summary>Specifies the list of exempt paths from all rate limit quotas. If empty no paths will be exempt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RateLimitExemptPaths { get; set; }
#nullable restore
#else
        public List<string> RateLimitExemptPaths { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.RateLimitQuotasConfigureRequest"/> and sets the default values.
        /// </summary>
        public RateLimitQuotasConfigureRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.RateLimitQuotasConfigureRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.RateLimitQuotasConfigureRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.RateLimitQuotasConfigureRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absolute_rate_limit_exempt_paths", n => { AbsoluteRateLimitExemptPaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "enable_rate_limit_audit_logging", n => { EnableRateLimitAuditLogging = n.GetBoolValue(); } },
                { "enable_rate_limit_response_headers", n => { EnableRateLimitResponseHeaders = n.GetBoolValue(); } },
                { "rate_limit_exempt_paths", n => { RateLimitExemptPaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("absolute_rate_limit_exempt_paths", AbsoluteRateLimitExemptPaths);
            writer.WriteBoolValue("enable_rate_limit_audit_logging", EnableRateLimitAuditLogging);
            writer.WriteBoolValue("enable_rate_limit_response_headers", EnableRateLimitResponseHeaders);
            writer.WriteCollectionOfPrimitiveValues<string>("rate_limit_exempt_paths", RateLimitExemptPaths);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
