// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RekeyRecoveryKeyAttemptInitializeRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies if using PGP-encrypted keys, whether Vault should also store a plaintext backup of the PGP-encrypted keys.</summary>
        public bool? Backup { get; set; }
        /// <summary>Specifies an array of PGP public keys used to encrypt the output recovery keys.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PgpKeys { get; set; }
#nullable restore
#else
        public List<string> PgpKeys { get; set; }
#endif
        /// <summary>Turns on verification functionality</summary>
        public bool? RequireVerification { get; set; }
        /// <summary>Specifies the number of shares to split the recovery key into.</summary>
        public int? SecretShares { get; set; }
        /// <summary>Specifies the number of shares required to reconstruct the recovery key.</summary>
        public int? SecretThreshold { get; set; }
        /// <summary>Specifies the number of shares that should be encrypted by the HSM and stored for auto-unsealing. Currently must be the same as `secret_shares`.</summary>
        public int? StoredShares { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.RekeyRecoveryKeyAttemptInitializeRequest"/> and sets the default values.
        /// </summary>
        public RekeyRecoveryKeyAttemptInitializeRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.RekeyRecoveryKeyAttemptInitializeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.RekeyRecoveryKeyAttemptInitializeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.RekeyRecoveryKeyAttemptInitializeRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backup", n => { Backup = n.GetBoolValue(); } },
                { "pgp_keys", n => { PgpKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "require_verification", n => { RequireVerification = n.GetBoolValue(); } },
                { "secret_shares", n => { SecretShares = n.GetIntValue(); } },
                { "secret_threshold", n => { SecretThreshold = n.GetIntValue(); } },
                { "stored_shares", n => { StoredShares = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("backup", Backup);
            writer.WriteCollectionOfPrimitiveValues<string>("pgp_keys", PgpKeys);
            writer.WriteBoolValue("require_verification", RequireVerification);
            writer.WriteIntValue("secret_shares", SecretShares);
            writer.WriteIntValue("secret_threshold", SecretThreshold);
            writer.WriteIntValue("stored_shares", StoredShares);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
