// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RekeyReadBackupKeyResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys? Keys { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys Keys { get; set; }
#endif
        /// <summary>The keys_base64 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys_base64? KeysBase64 { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys_base64 KeysBase64 { get; set; }
#endif
        /// <summary>The nonce property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nonce { get; set; }
#nullable restore
#else
        public string Nonce { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.RekeyReadBackupKeyResponse"/> and sets the default values.
        /// </summary>
        public RekeyReadBackupKeyResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.RekeyReadBackupKeyResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.RekeyReadBackupKeyResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.RekeyReadBackupKeyResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "keys", n => { Keys = n.GetObjectValue<global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys>(global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys.CreateFromDiscriminatorValue); } },
                { "keys_base64", n => { KeysBase64 = n.GetObjectValue<global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys_base64>(global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys_base64.CreateFromDiscriminatorValue); } },
                { "nonce", n => { Nonce = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys>("keys", Keys);
            writer.WriteObjectValue<global::VaultApi.Client.Models.RekeyReadBackupKeyResponse_keys_base64>("keys_base64", KeysBase64);
            writer.WriteStringValue("nonce", Nonce);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
