// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace VaultApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserpassWriteUserRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The metadata to be tied to generated entity alias. This should be a list or map containing the metadata in key value pairs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::VaultApi.Client.Models.UserpassWriteUserRequest_alias_metadata? AliasMetadata { get; set; }
#nullable restore
#else
        public global::VaultApi.Client.Models.UserpassWriteUserRequest_alias_metadata AliasMetadata { get; set; }
#endif
        /// <summary>Use &quot;token_bound_cidrs&quot; instead. If this and &quot;token_bound_cidrs&quot; are both specified, only &quot;token_bound_cidrs&quot; will be used.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BoundCidrs { get; set; }
#nullable restore
#else
        public List<string> BoundCidrs { get; set; }
#endif
        /// <summary>Use &quot;token_max_ttl&quot; instead. If this and &quot;token_max_ttl&quot; are both specified, only &quot;token_max_ttl&quot; will be used.</summary>
        [Obsolete("")]
        public TimeSpan? MaxTtl { get; set; }
        /// <summary>Password for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>Pre-hashed password in bcrypt format for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PasswordHash { get; set; }
#nullable restore
#else
        public string PasswordHash { get; set; }
#endif
        /// <summary>Use &quot;token_policies&quot; instead. If this and &quot;token_policies&quot; are both specified, only &quot;token_policies&quot; will be used.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Policies { get; set; }
#nullable restore
#else
        public List<string> Policies { get; set; }
#endif
        /// <summary>Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TokenBoundCidrs { get; set; }
#nullable restore
#else
        public List<string> TokenBoundCidrs { get; set; }
#endif
        /// <summary>If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.</summary>
        public TimeSpan? TokenExplicitMaxTtl { get; set; }
        /// <summary>The maximum lifetime of the generated token</summary>
        public TimeSpan? TokenMaxTtl { get; set; }
        /// <summary>If true, the &apos;default&apos; policy will not automatically be added to generated tokens</summary>
        public bool? TokenNoDefaultPolicy { get; set; }
        /// <summary>The maximum number of times a token may be used, a value of zero means unlimited</summary>
        public int? TokenNumUses { get; set; }
        /// <summary>If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. &quot;24h&quot;).</summary>
        public TimeSpan? TokenPeriod { get; set; }
        /// <summary>Comma-separated list of policies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TokenPolicies { get; set; }
#nullable restore
#else
        public List<string> TokenPolicies { get; set; }
#endif
        /// <summary>The initial ttl of the token to generate</summary>
        public TimeSpan? TokenTtl { get; set; }
        /// <summary>The type of token to generate, service or batch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenType { get; set; }
#nullable restore
#else
        public string TokenType { get; set; }
#endif
        /// <summary>Use &quot;token_ttl&quot; instead. If this and &quot;token_ttl&quot; are both specified, only &quot;token_ttl&quot; will be used.</summary>
        [Obsolete("")]
        public TimeSpan? Ttl { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Models.UserpassWriteUserRequest"/> and sets the default values.
        /// </summary>
        public UserpassWriteUserRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            TokenType = "default-service";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.UserpassWriteUserRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::VaultApi.Client.Models.UserpassWriteUserRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::VaultApi.Client.Models.UserpassWriteUserRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias_metadata", n => { AliasMetadata = n.GetObjectValue<global::VaultApi.Client.Models.UserpassWriteUserRequest_alias_metadata>(global::VaultApi.Client.Models.UserpassWriteUserRequest_alias_metadata.CreateFromDiscriminatorValue); } },
                { "bound_cidrs", n => { BoundCidrs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "max_ttl", n => { MaxTtl = n.GetTimeSpanValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "password_hash", n => { PasswordHash = n.GetStringValue(); } },
                { "policies", n => { Policies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "token_bound_cidrs", n => { TokenBoundCidrs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "token_explicit_max_ttl", n => { TokenExplicitMaxTtl = n.GetTimeSpanValue(); } },
                { "token_max_ttl", n => { TokenMaxTtl = n.GetTimeSpanValue(); } },
                { "token_no_default_policy", n => { TokenNoDefaultPolicy = n.GetBoolValue(); } },
                { "token_num_uses", n => { TokenNumUses = n.GetIntValue(); } },
                { "token_period", n => { TokenPeriod = n.GetTimeSpanValue(); } },
                { "token_policies", n => { TokenPolicies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "token_ttl", n => { TokenTtl = n.GetTimeSpanValue(); } },
                { "token_type", n => { TokenType = n.GetStringValue(); } },
                { "ttl", n => { Ttl = n.GetTimeSpanValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::VaultApi.Client.Models.UserpassWriteUserRequest_alias_metadata>("alias_metadata", AliasMetadata);
            writer.WriteCollectionOfPrimitiveValues<string>("bound_cidrs", BoundCidrs);
            writer.WriteTimeSpanValue("max_ttl", MaxTtl);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("password_hash", PasswordHash);
            writer.WriteCollectionOfPrimitiveValues<string>("policies", Policies);
            writer.WriteCollectionOfPrimitiveValues<string>("token_bound_cidrs", TokenBoundCidrs);
            writer.WriteTimeSpanValue("token_explicit_max_ttl", TokenExplicitMaxTtl);
            writer.WriteTimeSpanValue("token_max_ttl", TokenMaxTtl);
            writer.WriteBoolValue("token_no_default_policy", TokenNoDefaultPolicy);
            writer.WriteIntValue("token_num_uses", TokenNumUses);
            writer.WriteTimeSpanValue("token_period", TokenPeriod);
            writer.WriteCollectionOfPrimitiveValues<string>("token_policies", TokenPolicies);
            writer.WriteTimeSpanValue("token_ttl", TokenTtl);
            writer.WriteStringValue("token_type", TokenType);
            writer.WriteTimeSpanValue("ttl", Ttl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
