// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Identity.Persona.Id.Item;
namespace VaultApi.Client.Identity.Persona.Id
{
    /// <summary>
    /// Builds and executes requests for operations under \identity\persona\id
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>List all the alias IDs.</summary>
        public global::VaultApi.Client.Identity.Persona.Id.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Identity.Persona.Id.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Update, read or delete an alias ID.</summary>
        /// <param name="position">ID of the persona</param>
        /// <returns>A <see cref="global::VaultApi.Client.Identity.Persona.Id.Item.IdItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Identity.Persona.Id.Item.IdItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::VaultApi.Client.Identity.Persona.Id.Item.IdItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Persona.Id.IdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/persona/id", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Persona.Id.IdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/persona/id", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
