// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Storage.Raft.SnapshotAuto;
namespace VaultApi.Client.Sys.Storage.Raft
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\storage\raft
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RaftRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The snapshotAuto property</summary>
        public global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.SnapshotAutoRequestBuilder SnapshotAuto
        {
            get => new global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.SnapshotAutoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Storage.Raft.RaftRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RaftRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/storage/raft", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Storage.Raft.RaftRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RaftRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/storage/raft", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
