// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Kv.Destroy.Item;
namespace VaultApi.Client.Kv.Destroy
{
    /// <summary>
    /// Builds and executes requests for operations under \kv\destroy
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DestroyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Permanently removes one or more versions in the KV store</summary>
        /// <param name="position">Location of the secret.</param>
        /// <returns>A <see cref="global::VaultApi.Client.Kv.Destroy.Item.WithPathItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Kv.Destroy.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::VaultApi.Client.Kv.Destroy.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Kv.Destroy.DestroyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DestroyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kv/destroy", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Kv.Destroy.DestroyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DestroyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kv/destroy", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
