// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Sealwrap.Rewrap;
namespace VaultApi.Client.Sys.Sealwrap
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\sealwrap
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SealwrapRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rewrap property</summary>
        public global::VaultApi.Client.Sys.Sealwrap.Rewrap.RewrapRequestBuilder Rewrap
        {
            get => new global::VaultApi.Client.Sys.Sealwrap.Rewrap.RewrapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Sealwrap.SealwrapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SealwrapRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/sealwrap", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Sealwrap.SealwrapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SealwrapRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/sealwrap", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
