// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Replication.Dr;
using VaultApi.Client.Sys.Replication.Performance;
using VaultApi.Client.Sys.Replication.Primary;
using VaultApi.Client.Sys.Replication.Recover;
using VaultApi.Client.Sys.Replication.Reindex;
using VaultApi.Client.Sys.Replication.Secondary;
using VaultApi.Client.Sys.Replication.Status;
namespace VaultApi.Client.Sys.Replication
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\replication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReplicationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dr property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.DrRequestBuilder Dr
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.DrRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The performance property</summary>
        public global::VaultApi.Client.Sys.Replication.Performance.PerformanceRequestBuilder Performance
        {
            get => new global::VaultApi.Client.Sys.Replication.Performance.PerformanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The primary property</summary>
        public global::VaultApi.Client.Sys.Replication.Primary.PrimaryRequestBuilder Primary
        {
            get => new global::VaultApi.Client.Sys.Replication.Primary.PrimaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recover property</summary>
        public global::VaultApi.Client.Sys.Replication.Recover.RecoverRequestBuilder Recover
        {
            get => new global::VaultApi.Client.Sys.Replication.Recover.RecoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reindex property</summary>
        public global::VaultApi.Client.Sys.Replication.Reindex.ReindexRequestBuilder Reindex
        {
            get => new global::VaultApi.Client.Sys.Replication.Reindex.ReindexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secondary property</summary>
        public global::VaultApi.Client.Sys.Replication.Secondary.SecondaryRequestBuilder Secondary
        {
            get => new global::VaultApi.Client.Sys.Replication.Secondary.SecondaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::VaultApi.Client.Sys.Replication.Status.StatusRequestBuilder Status
        {
            get => new global::VaultApi.Client.Sys.Replication.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.ReplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReplicationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.ReplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReplicationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
