// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.LockedUsers.Item.Unlock;
namespace VaultApi.Client.Sys.LockedUsers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\locked-users\{mount_accessor}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMount_accessorItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The unlock property</summary>
        public global::VaultApi.Client.Sys.LockedUsers.Item.Unlock.UnlockRequestBuilder Unlock
        {
            get => new global::VaultApi.Client.Sys.LockedUsers.Item.Unlock.UnlockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.LockedUsers.Item.WithMount_accessorItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMount_accessorItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/locked-users/{mount_accessor}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.LockedUsers.Item.WithMount_accessorItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMount_accessorItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/locked-users/{mount_accessor}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
