// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Config.Auditing.RequestHeaders;
namespace VaultApi.Client.Sys.Config.Auditing
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\config\auditing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Lists the headers configured to be audited.</summary>
        public global::VaultApi.Client.Sys.Config.Auditing.RequestHeaders.RequestHeadersRequestBuilder RequestHeaders
        {
            get => new global::VaultApi.Client.Sys.Config.Auditing.RequestHeaders.RequestHeadersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Config.Auditing.AuditingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/config/auditing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Config.Auditing.AuditingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/config/auditing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
