// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Replication.Dr.Primary;
using VaultApi.Client.Sys.Replication.Dr.Secondary;
using VaultApi.Client.Sys.Replication.Dr.Status;
namespace VaultApi.Client.Sys.Replication.Dr
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\replication\dr
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DrRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The primary property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Primary.PrimaryRequestBuilder Primary
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Primary.PrimaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secondary property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.SecondaryRequestBuilder Secondary
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.SecondaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Status.StatusRequestBuilder Status
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Dr.DrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DrRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/dr", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Dr.DrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DrRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/dr", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
