// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Rekey.Backup;
using VaultApi.Client.Sys.Rekey.Init;
using VaultApi.Client.Sys.Rekey.RecoveryKeyBackup;
using VaultApi.Client.Sys.Rekey.Update;
using VaultApi.Client.Sys.Rekey.Verify;
namespace VaultApi.Client.Sys.Rekey
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\rekey
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RekeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Allows fetching or deleting the backup of the rotated unseal keys.</summary>
        public global::VaultApi.Client.Sys.Rekey.Backup.BackupRequestBuilder Backup
        {
            get => new global::VaultApi.Client.Sys.Rekey.Backup.BackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The init property</summary>
        public global::VaultApi.Client.Sys.Rekey.Init.InitRequestBuilder Init
        {
            get => new global::VaultApi.Client.Sys.Rekey.Init.InitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Allows fetching or deleting the backup of the rotated unseal keys.</summary>
        public global::VaultApi.Client.Sys.Rekey.RecoveryKeyBackup.RecoveryKeyBackupRequestBuilder RecoveryKeyBackup
        {
            get => new global::VaultApi.Client.Sys.Rekey.RecoveryKeyBackup.RecoveryKeyBackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::VaultApi.Client.Sys.Rekey.Update.UpdateRequestBuilder Update
        {
            get => new global::VaultApi.Client.Sys.Rekey.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::VaultApi.Client.Sys.Rekey.Verify.VerifyRequestBuilder Verify
        {
            get => new global::VaultApi.Client.Sys.Rekey.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Rekey.RekeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RekeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/rekey", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Rekey.RekeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RekeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/rekey", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
