// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Internal.Ui.AuthenticatedMessages;
using VaultApi.Client.Sys.Internal.Ui.FeatureFlags;
using VaultApi.Client.Sys.Internal.Ui.Mounts;
using VaultApi.Client.Sys.Internal.Ui.Namespaces;
using VaultApi.Client.Sys.Internal.Ui.ResultantAcl;
using VaultApi.Client.Sys.Internal.Ui.UnauthenticatedMessages;
namespace VaultApi.Client.Sys.Internal.Ui
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\internal\ui
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authenticatedMessages property</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.AuthenticatedMessages.AuthenticatedMessagesRequestBuilder AuthenticatedMessages
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.AuthenticatedMessages.AuthenticatedMessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Enabled feature flags. Internal API; its location, inputs, and outputs may change.</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.FeatureFlags.FeatureFlagsRequestBuilder FeatureFlags
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.FeatureFlags.FeatureFlagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Information about mounts returned according to their tuned visibility. Internal API; its location, inputs, and outputs may change.</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.Mounts.MountsRequestBuilder Mounts
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.Mounts.MountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Information about visible child namespaces. Internal API; its location, inputs, and outputs may change.</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.Namespaces.NamespacesRequestBuilder Namespaces
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.Namespaces.NamespacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Information about a token&apos;s resultant ACL. Internal API; its location, inputs, and outputs may change.</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.ResultantAcl.ResultantAclRequestBuilder ResultantAcl
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.ResultantAcl.ResultantAclRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unauthenticatedMessages property</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.UnauthenticatedMessages.UnauthenticatedMessagesRequestBuilder UnauthenticatedMessages
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.UnauthenticatedMessages.UnauthenticatedMessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.Ui.UiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal/ui", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.Ui.UiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal/ui", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
