// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Config;
using VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status;
namespace VaultApi.Client.Sys.Storage.Raft.SnapshotAuto
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\storage\raft\snapshot-auto
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SnapshotAutoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The config property</summary>
        public global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Config.ConfigRequestBuilder Config
        {
            get => new global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.StatusRequestBuilder Status
        {
            get => new global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.SnapshotAutoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SnapshotAutoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/storage/raft/snapshot-auto", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Storage.Raft.SnapshotAuto.SnapshotAutoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SnapshotAutoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/storage/raft/snapshot-auto", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
