// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Policies.Acl.Item;
namespace VaultApi.Client.Sys.Policies.Acl
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\policies\acl
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AclRequestBuilder : BaseRequestBuilder
    {
        /// <summary>List the configured access control policies.</summary>
        public global::VaultApi.Client.Sys.Policies.Acl.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::VaultApi.Client.Sys.Policies.Acl.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Read, Modify, or Delete an access control policy.</summary>
        /// <param name="position">The name of the policy. Example: &quot;ops&quot;</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Policies.Acl.Item.WithNameItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Policies.Acl.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::VaultApi.Client.Sys.Policies.Acl.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Policies.Acl.AclRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AclRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/policies/acl", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Policies.Acl.AclRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AclRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/policies/acl", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
