parameters:
  api:
    port_http: 8080
    api_image: "api:latest"
  vite_app:
    vite_app_image: "vite-app:latest"
  vault:
    vault_image: "vault:latest"
secrets:
  postgres:
    postgres_password: ""
  postgres_zitadel:
    postgres_zitadel_password: ""
  zitadel:
    zitadel_masterKey: ""
    zitadel_password: ""
    postgres_zitadel_password: ""
    ConnectionStrings__postgres_zitadel_db: ""
    POSTGRES_ZITADEL_DB_URI: ""
  api:
    ConnectionStrings__postgresdb: ""
    postgres_password: ""
    POSTGRESDB_URI: ""
    vault_token: ""
config:
  postgres:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  postgres_zitadel:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  zitadel:
    ZITADEL_EXTERNALDOMAIN: "localhost"
    ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: "false"
    zitadel_username: ""
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "false"
    ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "postgres"
    ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: "postgres"
    ZITADEL_DATABASE_POSTGRES_HOST: "postgres-zitadel-service"
    ZITADEL_DATABASE_POSTGRES_PORT: "5432"
    ZITADEL_DATABASE_POSTGRES_DATABASE: "postgres-zitadel-db"
    POSTGRES_ZITADEL_DB_HOST: "postgres-zitadel-service"
    POSTGRES_ZITADEL_DB_PORT: "5432"
    POSTGRES_ZITADEL_DB_USERNAME: "postgres"
    POSTGRES_ZITADEL_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-zitadel-service:5432/postgres-zitadel-db"
    POSTGRES_ZITADEL_DB_DATABASENAME: "postgres-zitadel-db"
  api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    POSTGRESDB_HOST: "postgres-service"
    POSTGRESDB_PORT: "5432"
    POSTGRESDB_USERNAME: "postgres"
    POSTGRESDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/postgresdb"
    POSTGRESDB_DATABASENAME: "postgresdb"
    VITE_APP_HTTP: "http://vite-app-service:5000"
    services__vite_app__http__0: "http://vite-app-service:5000"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "api"
  vite_app:
    NODE_ENV: "production"
    PORT: "5000"
    API_HTTP: ""
    services__api__http__0: ""
    API_HTTPS: ""
    YARP_ENABLE_STATIC_FILES: "true"
  vault:
    VAULT_ADDR: "http://127.0.0.1:8200"
