// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.ManagedKeys.Item.Item.Test.Sign;
namespace VaultApi.Client.Sys.ManagedKeys.Item.Item.Test
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\managed-keys\{type}\{name}\test
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The sign property</summary>
        public global::VaultApi.Client.Sys.ManagedKeys.Item.Item.Test.Sign.SignRequestBuilder Sign
        {
            get => new global::VaultApi.Client.Sys.ManagedKeys.Item.Item.Test.Sign.SignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ManagedKeys.Item.Item.Test.TestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/managed-keys/{type}/{name}/test", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ManagedKeys.Item.Item.Test.TestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/managed-keys/{type}/{name}/test", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
