// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace VaultApi.Client.Sys.VersionHistory
{
    /// <summary>List historical version changes sorted by installation time in ascending order.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetListQueryParameterType
    {
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        True,
        #pragma warning restore CS1591
    }
}
