// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VaultApi.Client.Identity.Entity.BatchDelete;
using VaultApi.Client.Identity.Entity.Id;
using VaultApi.Client.Identity.Entity.Merge;
using VaultApi.Client.Identity.Entity.Name;
using VaultApi.Client.Models;
namespace VaultApi.Client.Identity.Entity
{
    /// <summary>
    /// Create a new entity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Delete all of the entities provided</summary>
        public global::VaultApi.Client.Identity.Entity.BatchDelete.BatchDeleteRequestBuilder BatchDelete
        {
            get => new global::VaultApi.Client.Identity.Entity.BatchDelete.BatchDeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The id property</summary>
        public global::VaultApi.Client.Identity.Entity.Id.IdRequestBuilder Id
        {
            get => new global::VaultApi.Client.Identity.Entity.Id.IdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Merge two or more entities together</summary>
        public global::VaultApi.Client.Identity.Entity.Merge.MergeRequestBuilder Merge
        {
            get => new global::VaultApi.Client.Identity.Entity.Merge.MergeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The name property</summary>
        public global::VaultApi.Client.Identity.Entity.Name.NameRequestBuilder Name
        {
            get => new global::VaultApi.Client.Identity.Entity.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Entity.EntityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/entity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Entity.EntityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/entity", rawUrl)
        {
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::VaultApi.Client.Models.EntityCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::VaultApi.Client.Models.EntityCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::VaultApi.Client.Models.EntityCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::VaultApi.Client.Models.EntityCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Identity.Entity.EntityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VaultApi.Client.Identity.Entity.EntityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VaultApi.Client.Identity.Entity.EntityRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EntityRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
