// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter.Item;
namespace VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\replication\performance\secondary\dynamic-filter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DynamicFilterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VaultApi.Client.sys.replication.performance.secondary.dynamicFilter.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter.Item.DynamicFilterItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter.Item.DynamicFilterItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter.Item.DynamicFilterItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter.DynamicFilterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DynamicFilterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/performance/secondary/dynamic-filter", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Performance.Secondary.DynamicFilter.DynamicFilterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DynamicFilterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/performance/secondary/dynamic-filter", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
