// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Kv.Config;
using VaultApi.Client.Kv.Data;
using VaultApi.Client.Kv.Delete;
using VaultApi.Client.Kv.Destroy;
using VaultApi.Client.Kv.Metadata;
using VaultApi.Client.Kv.Subkeys;
using VaultApi.Client.Kv.Undelete;
using VaultApi.Client.Kv.Asterisk;
namespace VaultApi.Client.Kv
{
    /// <summary>
    /// Builds and executes requests for operations under \kv
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AsteriskDollar property</summary>
        public global::VaultApi.Client.Kv.Asterisk.RequestBuilder AsteriskDollar
        {
            get => new global::VaultApi.Client.Kv.Asterisk.RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Configures settings for the KV store</summary>
        public global::VaultApi.Client.Kv.Config.ConfigRequestBuilder Config
        {
            get => new global::VaultApi.Client.Kv.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The data property</summary>
        public global::VaultApi.Client.Kv.Data.DataRequestBuilder Data
        {
            get => new global::VaultApi.Client.Kv.Data.DataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::VaultApi.Client.Kv.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::VaultApi.Client.Kv.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The destroy property</summary>
        public global::VaultApi.Client.Kv.Destroy.DestroyRequestBuilder Destroy
        {
            get => new global::VaultApi.Client.Kv.Destroy.DestroyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::VaultApi.Client.Kv.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::VaultApi.Client.Kv.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subkeys property</summary>
        public global::VaultApi.Client.Kv.Subkeys.SubkeysRequestBuilder Subkeys
        {
            get => new global::VaultApi.Client.Kv.Subkeys.SubkeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The undelete property</summary>
        public global::VaultApi.Client.Kv.Undelete.UndeleteRequestBuilder Undelete
        {
            get => new global::VaultApi.Client.Kv.Undelete.UndeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Kv.KvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kv", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Kv.KvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kv", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
