// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VaultApi.Client.Sys.ActivationFlags.ActivationTest;
using VaultApi.Client.Sys.ActivationFlags.EnableScim;
using VaultApi.Client.Sys.ActivationFlags.ForceIdentityDeduplication;
using VaultApi.Client.Sys.ActivationFlags.OauthResourceServer;
namespace VaultApi.Client.Sys.ActivationFlags
{
    /// <summary>
    /// Returns information about Vault&apos;s features that require a one-time activation step.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivationFlagsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activationTest property</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.ActivationTest.ActivationTestRequestBuilder ActivationTest
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.ActivationTest.ActivationTestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enableScim property</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.EnableScim.EnableScimRequestBuilder EnableScim
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.EnableScim.EnableScimRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forceIdentityDeduplication property</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.ForceIdentityDeduplication.ForceIdentityDeduplicationRequestBuilder ForceIdentityDeduplication
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.ForceIdentityDeduplication.ForceIdentityDeduplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauthResourceServer property</summary>
        public global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.OauthResourceServerRequestBuilder OauthResourceServer
        {
            get => new global::VaultApi.Client.Sys.ActivationFlags.OauthResourceServer.OauthResourceServerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ActivationFlags.ActivationFlagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivationFlagsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/activation-flags", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.ActivationFlags.ActivationFlagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivationFlagsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/activation-flags", rawUrl)
        {
        }
        /// <summary>
        /// Returns the available and activated activation-flagged features.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the available and activated activation-flagged features.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.ActivationFlags.ActivationFlagsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VaultApi.Client.Sys.ActivationFlags.ActivationFlagsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VaultApi.Client.Sys.ActivationFlags.ActivationFlagsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActivationFlagsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
