---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "zitadel-login-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "zitadel-login"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  ZITADEL_API_URL: "{{ .Values.config.zitadel_login.ZITADEL_API_URL }}"
  NEXT_PUBLIC_BASE_PATH: "{{ .Values.config.zitadel_login.NEXT_PUBLIC_BASE_PATH }}"
  ZITADEL_SERVICE_USER_TOKEN_FILE: "{{ .Values.config.zitadel_login.ZITADEL_SERVICE_USER_TOKEN_FILE }}"
  CUSTOM_REQUEST_HEADERS: "{{ .Values.config.zitadel_login.CUSTOM_REQUEST_HEADERS }}"
