// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Identity.Alias;
using VaultApi.Client.Identity.Entity;
using VaultApi.Client.Identity.EntityAlias;
using VaultApi.Client.Identity.Group;
using VaultApi.Client.Identity.GroupAlias;
using VaultApi.Client.Identity.Lookup;
using VaultApi.Client.Identity.Mfa;
using VaultApi.Client.Identity.Oidc;
using VaultApi.Client.Identity.Persona;
namespace VaultApi.Client.Identity
{
    /// <summary>
    /// Builds and executes requests for operations under \identity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdentityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Create a new alias.</summary>
        public global::VaultApi.Client.Identity.Alias.AliasRequestBuilder Alias
        {
            get => new global::VaultApi.Client.Identity.Alias.AliasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Create a new entity</summary>
        public global::VaultApi.Client.Identity.Entity.EntityRequestBuilder Entity
        {
            get => new global::VaultApi.Client.Identity.Entity.EntityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Create a new alias.</summary>
        public global::VaultApi.Client.Identity.EntityAlias.EntityAliasRequestBuilder EntityAlias
        {
            get => new global::VaultApi.Client.Identity.EntityAlias.EntityAliasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Create a new group.</summary>
        public global::VaultApi.Client.Identity.Group.GroupRequestBuilder Group
        {
            get => new global::VaultApi.Client.Identity.Group.GroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Creates a new group alias, or updates an existing one.</summary>
        public global::VaultApi.Client.Identity.GroupAlias.GroupAliasRequestBuilder GroupAlias
        {
            get => new global::VaultApi.Client.Identity.GroupAlias.GroupAliasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lookup property</summary>
        public global::VaultApi.Client.Identity.Lookup.LookupRequestBuilder Lookup
        {
            get => new global::VaultApi.Client.Identity.Lookup.LookupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mfa property</summary>
        public global::VaultApi.Client.Identity.Mfa.MfaRequestBuilder Mfa
        {
            get => new global::VaultApi.Client.Identity.Mfa.MfaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oidc property</summary>
        public global::VaultApi.Client.Identity.Oidc.OidcRequestBuilder Oidc
        {
            get => new global::VaultApi.Client.Identity.Oidc.OidcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Create a new alias.</summary>
        public global::VaultApi.Client.Identity.Persona.PersonaRequestBuilder Persona
        {
            get => new global::VaultApi.Client.Identity.Persona.PersonaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
