// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Mounts.Auth.Item;
namespace VaultApi.Client.Sys.Mounts.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\mounts\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the VaultApi.Client.sys.mounts.auth.item collection</summary>
        /// <param name="position">Tune the configuration parameters for an auth path.</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Mounts.Auth.Item.WithPathItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.Mounts.Auth.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::VaultApi.Client.Sys.Mounts.Auth.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Mounts.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/mounts/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Mounts.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/mounts/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
