// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.AuditHash.Item;
namespace VaultApi.Client.Sys.AuditHash
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\audit-hash
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditHashRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The hash of the given string via the given audit backend</summary>
        /// <param name="position">The name of the backend. Cannot be delimited. Example: &quot;mysql&quot;</param>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.AuditHash.Item.WithPathItemRequestBuilder"/></returns>
        public global::VaultApi.Client.Sys.AuditHash.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::VaultApi.Client.Sys.AuditHash.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.AuditHash.AuditHashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditHashRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/audit-hash", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.AuditHash.AuditHashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditHashRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/audit-hash", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
