// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Internal.Counters.Activity;
using VaultApi.Client.Sys.Internal.Counters.Config;
using VaultApi.Client.Sys.Internal.Counters.Entities;
using VaultApi.Client.Sys.Internal.Counters.Requests;
namespace VaultApi.Client.Sys.Internal.Counters
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\internal\counters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CountersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Query the historical count of clients.</summary>
        public global::VaultApi.Client.Sys.Internal.Counters.Activity.ActivityRequestBuilder Activity
        {
            get => new global::VaultApi.Client.Sys.Internal.Counters.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Control the collection and reporting of client counts.</summary>
        public global::VaultApi.Client.Sys.Internal.Counters.Config.ConfigRequestBuilder Config
        {
            get => new global::VaultApi.Client.Sys.Internal.Counters.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Count of active entities in this Vault cluster.</summary>
        public global::VaultApi.Client.Sys.Internal.Counters.Entities.EntitiesRequestBuilder Entities
        {
            get => new global::VaultApi.Client.Sys.Internal.Counters.Entities.EntitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Currently unsupported. Previously, count of requests seen by this Vault cluster over time.</summary>
        public global::VaultApi.Client.Sys.Internal.Counters.Requests.RequestsRequestBuilder Requests
        {
            get => new global::VaultApi.Client.Sys.Internal.Counters.Requests.RequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.Counters.CountersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal/counters", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.Counters.CountersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal/counters", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
