// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Config;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Disable;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Enable;
using VaultApi.Client.Sys.Replication.Dr.Secondary.GeneratePublicKey;
using VaultApi.Client.Sys.Replication.Dr.Secondary.License;
using VaultApi.Client.Sys.Replication.Dr.Secondary.OperationToken;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Promote;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Recover;
using VaultApi.Client.Sys.Replication.Dr.Secondary.Reindex;
using VaultApi.Client.Sys.Replication.Dr.Secondary.UpdatePrimary;
namespace VaultApi.Client.Sys.Replication.Dr.Secondary
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\replication\dr\secondary
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecondaryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The config property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.ConfigRequestBuilder Config
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disable property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Disable.DisableRequestBuilder Disable
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enable property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Enable.EnableRequestBuilder Enable
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The generatePublicKey property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.GeneratePublicKey.GeneratePublicKeyRequestBuilder GeneratePublicKey
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.GeneratePublicKey.GeneratePublicKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The license property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.License.LicenseRequestBuilder License
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.License.LicenseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The operationToken property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.OperationToken.OperationTokenRequestBuilder OperationToken
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.OperationToken.OperationTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The promote property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Promote.PromoteRequestBuilder Promote
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Promote.PromoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recover property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Recover.RecoverRequestBuilder Recover
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Recover.RecoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reindex property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.Reindex.ReindexRequestBuilder Reindex
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.Reindex.ReindexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updatePrimary property</summary>
        public global::VaultApi.Client.Sys.Replication.Dr.Secondary.UpdatePrimary.UpdatePrimaryRequestBuilder UpdatePrimary
        {
            get => new global::VaultApi.Client.Sys.Replication.Dr.Secondary.UpdatePrimary.UpdatePrimaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Dr.Secondary.SecondaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecondaryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/dr/secondary", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Replication.Dr.Secondary.SecondaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecondaryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/replication/dr/secondary", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
