---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-zitadel-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-zitadel"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres_zitadel.postgres_zitadel_password }}"
type: "Opaque"
