---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"
metadata:
  name: "localtest-gateway-ui-localtest-me-route"
spec:
  parentRefs:
    - name: "localtest-gateway"
  hostnames:
    - "ui.localtest.me"
  rules:
    - matches:
        - path:
            type: "PathPrefix"
            value: "/"
      backendRefs:
        - name: "vite-app-service"
          port: 5000
