// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Plugins.Catalog;
using VaultApi.Client.Sys.Plugins.Pins;
using VaultApi.Client.Sys.Plugins.Reload;
using VaultApi.Client.Sys.Plugins.Runtimes;
namespace VaultApi.Client.Sys.Plugins
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\plugins
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PluginsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Lists all the plugins known to Vault</summary>
        public global::VaultApi.Client.Sys.Plugins.Catalog.CatalogRequestBuilder Catalog
        {
            get => new global::VaultApi.Client.Sys.Plugins.Catalog.CatalogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Lists all the pinned plugin versions known to Vault</summary>
        public global::VaultApi.Client.Sys.Plugins.Pins.PinsRequestBuilder Pins
        {
            get => new global::VaultApi.Client.Sys.Plugins.Pins.PinsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reload property</summary>
        public global::VaultApi.Client.Sys.Plugins.Reload.ReloadRequestBuilder Reload
        {
            get => new global::VaultApi.Client.Sys.Plugins.Reload.ReloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runtimes property</summary>
        public global::VaultApi.Client.Sys.Plugins.Runtimes.RuntimesRequestBuilder Runtimes
        {
            get => new global::VaultApi.Client.Sys.Plugins.Runtimes.RuntimesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Plugins.PluginsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PluginsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/plugins", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Plugins.PluginsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PluginsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/plugins", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
