---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "zitadel-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "zitadel"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  ZITADEL_EXTERNALDOMAIN: "{{ .Values.config.zitadel.ZITADEL_EXTERNALDOMAIN }}"
  ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: "{{ .Values.config.zitadel.ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED }}"
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: "{{ .Values.config.zitadel.zitadel_username }}"
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED }}"
  ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_USER_USERNAME }}"
  ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME }}"
  ZITADEL_DATABASE_POSTGRES_HOST: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_HOST }}"
  ZITADEL_DATABASE_POSTGRES_PORT: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_PORT }}"
  ZITADEL_DATABASE_POSTGRES_DATABASE: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_DATABASE }}"
  POSTGRES_ZITADEL_DB_HOST: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_HOST }}"
  POSTGRES_ZITADEL_DB_PORT: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_PORT }}"
  POSTGRES_ZITADEL_DB_USERNAME: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_USERNAME }}"
  POSTGRES_ZITADEL_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_JDBCCONNECTIONSTRING }}"
  POSTGRES_ZITADEL_DB_DATABASENAME: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_DATABASENAME }}"
  ZITADEL_TLSMODE: "{{ .Values.config.zitadel.ZITADEL_TLSMODE }}"
