---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "zitadel-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "zitadel"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  ZITADEL_TLS_ENABLED: "{{ .Values.config.zitadel.ZITADEL_TLS_ENABLED }}"
  ZITADEL_EXTERNALSECURE: "{{ .Values.config.zitadel.ZITADEL_EXTERNALSECURE }}"
  ZITADEL_EXTERNALDOMAIN: "{{ .Values.config.zitadel.ZITADEL_EXTERNALDOMAIN }}"
  ZITADEL_EXTERNALPORT: "{{ .Values.config.zitadel.ZITADEL_EXTERNALPORT }}"
  ZITADEL_DATABASE_POSTGRES_HOST: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_HOST }}"
  ZITADEL_DATABASE_POSTGRES_PORT: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_PORT }}"
  ZITADEL_DATABASE_POSTGRES_DATABASE: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_DATABASE }}"
  ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME }}"
  ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "{{ .Values.config.zitadel.ZITADEL_DATABASE_POSTGRES_USER_USERNAME }}"
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME }}"
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED }}"
  ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: "{{ .Values.config.zitadel.ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED }}"
  ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: "{{ .Values.config.zitadel.ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI }}"
  ZITADEL_OIDC_DEFAULTLOGINURLV2: "{{ .Values.config.zitadel.ZITADEL_OIDC_DEFAULTLOGINURLV2 }}"
  ZITADEL_OIDC_DEFAULTLOGOUTURLV2: "{{ .Values.config.zitadel.ZITADEL_OIDC_DEFAULTLOGOUTURLV2 }}"
  ZITADEL_SAML_DEFAULTLOGINURLV2: "{{ .Values.config.zitadel.ZITADEL_SAML_DEFAULTLOGINURLV2 }}"
  ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH }}"
  ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME }}"
  ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME }}"
  ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: "{{ .Values.config.zitadel.ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE }}"
  POSTGRES_ZITADEL_DB_HOST: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_HOST }}"
  POSTGRES_ZITADEL_DB_PORT: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_PORT }}"
  POSTGRES_ZITADEL_DB_USERNAME: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_USERNAME }}"
  POSTGRES_ZITADEL_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_JDBCCONNECTIONSTRING }}"
  POSTGRES_ZITADEL_DB_DATABASENAME: "{{ .Values.config.zitadel.POSTGRES_ZITADEL_DB_DATABASENAME }}"
