---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "zitadel-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "zitadel"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ZITADEL_MASTERKEY: "{{ .Values.secrets.zitadel.zitadel_masterKey }}"
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: "{{ .Values.secrets.zitadel.zitadel_password }}"
  ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "{{ .Values.secrets.zitadel.postgres_zitadel_password }}"
  ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "{{ .Values.secrets.zitadel.postgres_zitadel_password }}"
  ConnectionStrings__postgres-zitadel-db: "Host=postgres-zitadel-service;Port=5432;Username=postgres;Password={{ .Values.secrets.zitadel.postgres_zitadel_password }};Database=postgres-zitadel-db"
  POSTGRES_ZITADEL_DB_PASSWORD: "{{ .Values.secrets.zitadel.postgres_zitadel_password }}"
  POSTGRES_ZITADEL_DB_URI: "postgresql://postgres:{{ .Values.secrets.zitadel.postgres_zitadel_password }}@postgres-zitadel-service:5432/postgres-zitadel-db"
type: "Opaque"
