---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "vite-app-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "vite-app"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  NODE_ENV: "{{ .Values.config.vite_app.NODE_ENV }}"
  PORT: "{{ .Values.config.vite_app.PORT }}"
  API_HTTP: "{{ .Values.config.vite_app.API_HTTP }}"
  services__api__http__0: "{{ .Values.config.vite_app.services__api__http__0 }}"
  API_HTTPS: "{{ .Values.config.vite_app.API_HTTPS }}"
  YARP_ENABLE_STATIC_FILES: "{{ .Values.config.vite_app.YARP_ENABLE_STATIC_FILES }}"
