// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Identity.Lookup.Entity;
using VaultApi.Client.Identity.Lookup.Group;
namespace VaultApi.Client.Identity.Lookup
{
    /// <summary>
    /// Builds and executes requests for operations under \identity\lookup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LookupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Query entities based on various properties.</summary>
        public global::VaultApi.Client.Identity.Lookup.Entity.EntityRequestBuilder Entity
        {
            get => new global::VaultApi.Client.Identity.Lookup.Entity.EntityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Query groups based on various properties.</summary>
        public global::VaultApi.Client.Identity.Lookup.Group.GroupRequestBuilder Group
        {
            get => new global::VaultApi.Client.Identity.Lookup.Group.GroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Lookup.LookupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LookupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/lookup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Identity.Lookup.LookupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LookupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/lookup", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
