// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using VaultApi.Client.Sys.Internal.Counters;
using VaultApi.Client.Sys.Internal.Inspect;
using VaultApi.Client.Sys.Internal.Specs;
using VaultApi.Client.Sys.Internal.Ui;
namespace VaultApi.Client.Sys.Internal
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\internal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InternalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The counters property</summary>
        public global::VaultApi.Client.Sys.Internal.Counters.CountersRequestBuilder Counters
        {
            get => new global::VaultApi.Client.Sys.Internal.Counters.CountersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inspect property</summary>
        public global::VaultApi.Client.Sys.Internal.Inspect.InspectRequestBuilder Inspect
        {
            get => new global::VaultApi.Client.Sys.Internal.Inspect.InspectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The specs property</summary>
        public global::VaultApi.Client.Sys.Internal.Specs.SpecsRequestBuilder Specs
        {
            get => new global::VaultApi.Client.Sys.Internal.Specs.SpecsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ui property</summary>
        public global::VaultApi.Client.Sys.Internal.Ui.UiRequestBuilder Ui
        {
            get => new global::VaultApi.Client.Sys.Internal.Ui.UiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.InternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Internal.InternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/internal", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
