// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using VaultApi.Client.Models;
namespace VaultApi.Client.Sys.Billing.Overview
{
    /// <summary>
    /// Builds and executes requests for operations under \sys\billing\overview
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OverviewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OverviewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/billing/overview{?refresh_data*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OverviewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sys/billing/overview{?refresh_data*}", rawUrl)
        {
        }
        /// <summary>
        /// Reports consumption billing metrics for the current and previous months.
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Models.SystemReadBillingOverviewResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::VaultApi.Client.Models.SystemReadBillingOverviewResponse?> GetAsync(Action<RequestConfiguration<global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder.OverviewRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::VaultApi.Client.Models.SystemReadBillingOverviewResponse> GetAsync(Action<RequestConfiguration<global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder.OverviewRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::VaultApi.Client.Models.SystemReadBillingOverviewResponse>(requestInfo, global::VaultApi.Client.Models.SystemReadBillingOverviewResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Reports consumption billing metrics for the current and previous months.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder.OverviewRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder.OverviewRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Reports consumption billing metrics for the current and previous months.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OverviewRequestBuilderGetQueryParameters 
        {
            /// <summary>If set, updates the billing counts for the current month before returning. This is an expensive operation with potential performance impact and should be used sparingly.</summary>
            [QueryParameter("refresh_data")]
            public bool? RefreshData { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OverviewRequestBuilderGetRequestConfiguration : RequestConfiguration<global::VaultApi.Client.Sys.Billing.Overview.OverviewRequestBuilder.OverviewRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
