# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Integration Tests
      run: dotnet test -e ASPNETCORE_ENVIRONMENT=Test --no-build --verbosity normal --project tests/ApiIntegrationTests/ApiIntegrationTests/ApiIntegrationTests.csproj
    - name: End2End Tests
      if: github.event_name == 'workflow_dispatch'
      run: dotnet test -e ASPNETCORE_ENVIRONMENT=Test --no-build --verbosity normal --project tests/EndToEndTests/EndToEndTests.csproj
    - name: Format
      run: dotnet format
